<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Malek M. Itani">
<meta name="dcterms.date" content="2026-06-16">
<meta name="keywords" content="breast MRI, radiomics, phenotype discovery, ComBat harmonization, acquisition confounding, cluster stability, imaging AI reproducibility">
<meta name="description" content="Detecting sensor induced effects on high dimensional data.">

<title>Acquisition-Aware Falsification of Unsupervised Radiomic Phenotypes in Multi-Vendor Breast MRI – Malek M. Itani</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../assets/img/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-73b0ff3878a4e6fc3716dc69a6aaefa3.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-a60fab2f8a066d0ce7bf48d8b28043cc.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-73b0ff3878a4e6fc3716dc69a6aaefa3.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-105edf8004f9848bb1c5b5c0f91cc130.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-e045ed411a9396aabaef6f4bdfc2100d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-105edf8004f9848bb1c5b5c0f91cc130.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Acquisition-Aware Falsification of Unsupervised Radiomic Phenotypes in Multi-Vendor Breast MRI – Malek M. Itani">
<meta property="og:description" content="Detecting sensor induced effects on high dimensional data.">
<meta property="og:image" content="https://MalekItani.com/research/stability-trap/figures/fig-thumb-light.svg">
<meta property="og:site_name" content="Malek M. Itani">
<meta property="og:image:alt" content="Two scatterplots of the same points, coloured by cluster and by scanner — indistinguishable">
<meta name="twitter:title" content="Acquisition-Aware Falsification of Unsupervised Radiomic Phenotypes in Multi-Vendor Breast MRI – Malek M. Itani">
<meta name="twitter:description" content="Detecting sensor induced effects on high dimensional data.">
<meta name="twitter:image" content="https://MalekItani.com/research/stability-trap/figures/fig-thumb-light.svg">
<meta name="twitter:image:alt" content="Two scatterplots of the same points, coloured by cluster and by scanner — indistinguishable">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../assets/img/logo.svg" alt="Site logo" class="navbar-logo light-content">
    <img src="../../assets/img/logo.svg" alt="Site logo" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Malek M. Itani</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../blog/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../research/index.html"> 
<span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../prototypes/index.html"> 
<span class="menu-text">Prototypes</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About me</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/" target="_blank"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/" target="_blank"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../blog/index.xml"> <i class="bi bi-rss" role="img" aria-label="RSS feed">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#sec-verdict" id="toc-sec-verdict" class="nav-link active" data-scroll-target="#sec-verdict">What survives, and what does not</a></li>
  <li><a href="#sec-chain" id="toc-sec-chain" class="nav-link" data-scroll-target="#sec-chain">The falsification chain</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#background-and-rationale" id="toc-background-and-rationale" class="nav-link" data-scroll-target="#background-and-rationale"><span class="header-section-number">2</span> Background and rationale</a>
  <ul class="collapse">
  <li><a href="#radiomic-phenotype-discovery" id="toc-radiomic-phenotype-discovery" class="nav-link" data-scroll-target="#radiomic-phenotype-discovery"><span class="header-section-number">2.1</span> Radiomic phenotype discovery</a></li>
  <li><a href="#supervised-versus-unsupervised-settings" id="toc-supervised-versus-unsupervised-settings" class="nav-link" data-scroll-target="#supervised-versus-unsupervised-settings"><span class="header-section-number">2.2</span> Supervised versus unsupervised settings</a></li>
  <li><a href="#technical-variance-in-radiomics" id="toc-technical-variance-in-radiomics" class="nav-link" data-scroll-target="#technical-variance-in-radiomics"><span class="header-section-number">2.3</span> Technical variance in radiomics</a></li>
  <li><a href="#harmonization-and-its-limits" id="toc-harmonization-and-its-limits" class="nav-link" data-scroll-target="#harmonization-and-its-limits"><span class="header-section-number">2.4</span> Harmonization and its limits</a></li>
  <li><a href="#the-validation-gap" id="toc-the-validation-gap" class="nav-link" data-scroll-target="#the-validation-gap"><span class="header-section-number">2.5</span> The validation gap</a></li>
  </ul></li>
  <li><a href="#materials-and-methods" id="toc-materials-and-methods" class="nav-link" data-scroll-target="#materials-and-methods"><span class="header-section-number">3</span> Materials and methods</a>
  <ul class="collapse">
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="header-section-number">3.1</span> Data</a></li>
  <li><a href="#standard-phenotype-discovery" id="toc-standard-phenotype-discovery" class="nav-link" data-scroll-target="#standard-phenotype-discovery"><span class="header-section-number">3.2</span> Standard phenotype discovery</a></li>
  <li><a href="#falsification-chain-and-technical-adjudication" id="toc-falsification-chain-and-technical-adjudication" class="nav-link" data-scroll-target="#falsification-chain-and-technical-adjudication"><span class="header-section-number">3.3</span> Falsification chain and technical adjudication</a></li>
  <li><a href="#clinical-and-biomarker-evaluation" id="toc-clinical-and-biomarker-evaluation" class="nav-link" data-scroll-target="#clinical-and-biomarker-evaluation"><span class="header-section-number">3.4</span> Clinical and biomarker evaluation</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">4</span> Results</a>
  <ul class="collapse">
  <li><a href="#sec-km1" id="toc-sec-km1" class="nav-link" data-scroll-target="#sec-km1"><span class="header-section-number">4.1</span> A standard workflow produces a plausible but fragile discovery</a></li>
  <li><a href="#sec-km2" id="toc-sec-km2" class="nav-link" data-scroll-target="#sec-km2"><span class="header-section-number">4.2</span> The phenotype is acquisition-dominated, not subtype-defined</a></li>
  <li><a href="#sec-km3" id="toc-sec-km3" class="nav-link" data-scroll-target="#sec-km3"><span class="header-section-number">4.3</span> Harmonization preserves stability and destroys identity</a></li>
  <li><a href="#sec-km4" id="toc-sec-km4" class="nav-link" data-scroll-target="#sec-km4"><span class="header-section-number">4.4</span> Neither the survival signal nor the residual structure supports a biomarker claim</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">5</span> Discussion</a>
  <ul class="collapse">
  <li><a href="#the-negative-result-is-the-result" id="toc-the-negative-result-is-the-result" class="nav-link" data-scroll-target="#the-negative-result-is-the-result"><span class="header-section-number">5.1</span> The negative result is the result</a></li>
  <li><a href="#the-danger-is-in-the-language" id="toc-the-danger-is-in-the-language" class="nav-link" data-scroll-target="#the-danger-is-in-the-language"><span class="header-section-number">5.2</span> The danger is in the language</a></li>
  <li><a href="#stability-and-identity-are-separate-validation-targets" id="toc-stability-and-identity-are-separate-validation-targets" class="nav-link" data-scroll-target="#stability-and-identity-are-separate-validation-targets"><span class="header-section-number">5.3</span> Stability and identity are separate validation targets</a></li>
  <li><a href="#why-within-vendor-recovery-differs" id="toc-why-within-vendor-recovery-differs" class="nav-link" data-scroll-target="#why-within-vendor-recovery-differs"><span class="header-section-number">5.4</span> Why within-vendor recovery differs</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">5.5</span> Limitations</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">6</span> Conclusion</a></li>
  <li><a href="#sec-supplement" id="toc-sec-supplement" class="nav-link" data-scroll-target="#sec-supplement"><span class="header-section-number">7</span> Supplementary material</a></li>
  <li><a href="#sec-repro" id="toc-sec-repro" class="nav-link" data-scroll-target="#sec-repro">Reproducibility</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Acquisition-Aware Falsification of Unsupervised Radiomic Phenotypes in Multi-Vendor Breast MRI</h1>
<p class="subtitle lead">A falsification framework for acquisition-driven radiomic phenotypes</p>
  <div class="quarto-categories">
    <div class="quarto-category">radiomics</div>
    <div class="quarto-category">medical imaging</div>
    <div class="quarto-category">clustering</div>
    <div class="quarto-category">reproducibility</div>
  </div>
  </div>

<div>
  <div class="description">
    <p>Detecting sensor induced effects on high dimensional data.</p>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Malek M. Itani </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 16, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>We do not offer another radiomic phenotype from breast MRI. We expose a failure mode that survives standard internal validation: the <strong>stability trap</strong>, in which a partition is reproducible under resampling, looks prognostic, and has no biology underneath it. Running a conventional unsupervised pipeline on a 922-patient multi-vendor breast-MRI cohort produced exactly the kind of result that invites over-interpretation — a stable two-cluster partition with enhancement- and vascularity-like feature differences and a recurrence-free survival split in HR+/HER2+ disease. Scanner identity and pulse-sequence basis were each strongly associated with that partition; molecular subtype and whole-cohort recurrence were not. Manufacturer residualization and ComBat both removed the survival association and preserved internal clusterability while replacing the patient partition entirely. We report this as a falsification, not a biomarker, and propose the minimum acquisition-aware checks a phenotype claim should have to survive.</p>
  </div>
</div>

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>breast MRI, radiomics, phenotype discovery, ComBat harmonization, acquisition confounding, cluster stability, imaging AI reproducibility</p>
  </div>
</div>

</header>


<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>The result is a negative result
</div>
</div>
<div class="callout-body-container callout-body">
<p>Everything below was produced by a pipeline that a reviewer would recognise as standard. It passes the checks such pipelines are usually asked to pass. It is still wrong. That is the point of the paper.</p>
</div>
</div>
<section id="sec-verdict" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="sec-verdict">What survives, and what does not</h2>
<div class="cell" data-execution_count="2">
<div id="tbl-verdict" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-verdict-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Claim status after acquisition-aware falsification. Every claim a reader would want to make from the raw discovery fails except the one about reproducibility.
</figcaption>
<div aria-describedby="tbl-verdict-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="2">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Claim</th>
<th style="text-align: left;">Status</th>
<th style="text-align: left;">Evidence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">The raw two-cluster partition is internally stable</td>
<td style="text-align: left;">✅ <strong>Supported</strong></td>
<td style="text-align: left;">Mean bootstrap ARI 0.893 across 20 × 80% subsamples</td>
</tr>
<tr class="even">
<td style="text-align: left;">Its separating features read as vascularity</td>
<td style="text-align: left;">✅ <strong>Supported</strong></td>
<td style="text-align: left;">SER / PE enhancement-texture descriptors,</td>
</tr>
<tr class="odd">
<td style="text-align: left;">It separates recurrence-free survival in HR+/HER2+</td>
<td style="text-align: left;">⚠️ <strong>Unadjusted only</strong></td>
<td style="text-align: left;">Log-rank p = 0.010; HR 4.76 → 2.48 (p = 0.29) once manufacturer enters</td>
</tr>
<tr class="even">
<td style="text-align: left;">It is defined by molecular subtype</td>
<td style="text-align: left;">❌ <strong>Not supported</strong></td>
<td style="text-align: left;">χ² p = 0.146; η² on PC1 = 0.005</td>
</tr>
<tr class="odd">
<td style="text-align: left;">It is defined by acquisition</td>
<td style="text-align: left;">✅ <strong>Supported</strong></td>
<td style="text-align: left;">Manufacturer p = 8.0 × 10⁻¹⁰⁴; TR η² on PC1 = 0.755</td>
</tr>
<tr class="even">
<td style="text-align: left;">It survives harmonization as the same phenotype</td>
<td style="text-align: left;">❌ <strong>Not supported</strong></td>
<td style="text-align: left;">ARI vs raw labels = 0.056 (residualized), 0.065 (ComBat)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The post-harmonization structure meets biomarker criteria</td>
<td style="text-align: left;">❌ <strong>Not supported</strong></td>
<td style="text-align: left;">Strongest association is with tumour size, not outcome</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="sec-chain" class="level1 unnumbered">
<h1 class="unnumbered">The falsification chain</h1>
<p>The contribution is a procedure, so it is worth stating as one. Each stage asks a question that a stability metric cannot answer, and each has a failing answer in this cohort.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-chain" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-chain-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-chain">flowchart TB
    A["&lt;b&gt;1 · Standard discovery&lt;/b&gt;&lt;br/&gt;PCA → k-means → internal validity → bootstrap"]
    B["&lt;b&gt;2 · Technical adjudication&lt;/b&gt;&lt;br/&gt;clusters and leading PCs against acquisition vs biology"]
    C["&lt;b&gt;3 · Harmonization stress test&lt;/b&gt;&lt;br/&gt;residualize on manufacturer, ComBat, re-discover, compare partitions"]
    D["&lt;b&gt;4 · Biomarker adjudication&lt;/b&gt;&lt;br/&gt;prespecified criteria on the post-harmonization structure"]
    X(["&lt;b&gt;Claim falsified&lt;/b&gt; — downgrade to false positive"])
    A -- "&lt;b&gt;Stable?&lt;/b&gt; yes — bootstrap ARI 0.893" --&gt; B
    B -- "&lt;b&gt;Biology-led?&lt;/b&gt; no — manufacturer p = 8×10⁻¹⁰⁴, subtype p = 0.15" --&gt; C
    C -- "&lt;b&gt;Same patients?&lt;/b&gt; no — ARI vs raw 0.056 / 0.065" --&gt; D
    D -- "&lt;b&gt;Criteria met?&lt;/b&gt; no on all four" --&gt; X
    classDef stage fill:#f4f3f0,stroke:#c9c5bd,stroke-width:1px,color:#14181d;
    classDef verdict fill:#f6ecea,stroke:#8a2f2f,stroke-width:1px,color:#8a2f2f;
    class A,B,C,D stage;
    class X verdict;
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-chain-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: The acquisition-aware falsification chain. Each stage asks a question that a stability metric cannot answer; the edge labels carry this cohort’s answers. The claim survives stage 1 and fails every stage after it.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>The stability trap
</div>
</div>
<div class="callout-body-container callout-body">
<p>A partition can be <strong>reproducible</strong> — the same solution recovered from resampled data — without being <strong>valid</strong> — the same patients grouped for the same reason. Bootstrap stability measures the first. Almost every unsupervised radiomics paper reports the first and concludes the second. When the dominant source of variance in a feature matrix is the scanner, the scanner’s structure is itself perfectly reproducible, and stability certifies it.</p>
</div>
</div>
</section>
<section id="introduction" class="level1 page-columns page-full" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Radiomics promises latent imaging subgroups — phenotypes invisible to standard labelling. Breast MRI and dynamic contrast-enhanced imaging yield quantitative features describing heterogeneity in tumour morphology, vascularity and cellularity, and unsupervised learning offers to find structure in them. In theory this lets clinicians recover stable, biologically meaningful groupings that go beyond receptor-based labels <span class="citation" data-cites="lambin2012">(<a href="#ref-lambin2012" role="doc-biblioref">Lambin et al. 2012</a>)</span>.</p>
<p>In practice, multi-vendor datasets have shown that acquisition variables — manufacturer, pulse-sequence parameters, field strength, voxel geometry, reconstruction choices, acquisition timing — can drive inference <span class="citation" data-cites="zwanenburg2020">(<a href="#ref-zwanenburg2020" role="doc-biblioref"><span class="nocase">Zwanenburg et al.</span> 2020</a>)</span>. In high dimensions even small acquisition effects can dominate the feature space after dimensionality reduction, and a clustering algorithm will then recover a partition defined by technology rather than biology.</p>
<p>The validation practices in use measure reproducibility, not validity, and cannot distinguish a biologically meaningful phenotype from a technically induced one <span class="citation" data-cites="handl2005">(<a href="#ref-handl2005" role="doc-biblioref">Handl et al. 2005</a>)</span>. That gap is what we call the <strong>stability trap</strong>: the inference that a partition is biologically valid because the technical artifact underneath it is stable and reproducible.</p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">Everything downstream follows from one asymmetry: stability is cheap to measure and identity is not. Only one of the two is routinely reported.</span></div></div>
<p>This study therefore treats discovery and stability as the <em>beginning</em> of phenotype validation rather than its endpoint, and proposes a falsification chain that subjects any candidate phenotype to acquisition-aware challenges designed to expose technical confounding (<a href="#fig-chain" class="quarto-xref">Figure&nbsp;1</a>).</p>
<p>The first stage evaluates the raw feature space, testing whether the dominant principal components track biological or technical variables. The second stress-tests cluster identity: a real biological phenotype should survive manufacturer residualization and ComBat harmonization, so discovery is repeated after manufacturer effects are removed. The third re-evaluates the clinical interpretation after adjustment and across harmonization strategies.</p>
<p>Applying this to 922 breast-MRI patients, we first produce a stable two-cluster phenotype with enhancement-dominant, vascularity-like characteristics and an apparent HR+/HER2+ recurrence-free survival signal — and then show that the dominant variance axes are acquisition, not biology. The contribution is methodological rather than biomarker-driven: a phenotype can be internally stable, visually interpretable, and apparently prognostic while failing every test of biological identity.</p>
</section>
<section id="background-and-rationale" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Background and rationale</h1>
<section id="radiomic-phenotype-discovery" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="radiomic-phenotype-discovery"><span class="header-section-number">2.1</span> Radiomic phenotype discovery</h2>
<p>Radiomics extracts quantitative information from routine images, promising knowledge of tumour phenotype not captured by visual interpretation, and positioning imaging as a bridge to personalized medicine alongside histology, genomics and clinical covariates <span class="citation" data-cites="lambin2012">(<a href="#ref-lambin2012" role="doc-biblioref">Lambin et al. 2012</a>)</span>. Breast MRI is a particularly relevant modality: dynamic contrast-enhanced, diffusion-weighted and T2-weighted imaging together with enhancement kinetics carry information on vascularity, cellularity, morphology and tissue heterogeneity <span class="citation" data-cites="pinker2018">(<a href="#ref-pinker2018" role="doc-biblioref">Pinker et al. 2018</a>)</span>.</p>
<p>Most prior work is supervised, but the unsupervised setting is where phenotype discovery lives: patients are clustered on the feature space alone, and the resulting clusters are then examined for associations with prognosis, molecular subtype, immune state, stromal composition or pathway activity <span class="citation" data-cites="li2018">(<a href="#ref-li2018" role="doc-biblioref">Li et al. 2018</a>)</span>. This is the route by which image-derived cancer subtypes have been proposed <span class="citation" data-cites="yamamoto2012 aerts2014">(<a href="#ref-yamamoto2012" role="doc-biblioref">Yamamoto et al. 2012</a>; <a href="#ref-aerts2014" role="doc-biblioref">Aerts et al. 2014</a>)</span>, and there is broad agreement on the potential of radiomics to describe biological variation in tumours <span class="citation" data-cites="gillies2016">(<a href="#ref-gillies2016" role="doc-biblioref">Gillies et al. 2016</a>)</span>.</p>
</section>
<section id="supervised-versus-unsupervised-settings" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="supervised-versus-unsupervised-settings"><span class="header-section-number">2.2</span> Supervised versus unsupervised settings</h2>
<p>What separates the two is a failure mode that supervision partly avoids. With outcome labels that exist <em>outside</em> the feature space, model performance is judged against a predefined endpoint — molecular subtype, recurrence, treatment response — which limits the influence of technical confounding on inference <span class="citation" data-cites="parmar2015">(<a href="#ref-parmar2015" role="doc-biblioref">Parmar et al. 2015</a>)</span>. This is much of why supervised radiomics has moved toward clinical use faster than unsupervised radiomics has <span class="citation" data-cites="park2020">(<a href="#ref-park2020" role="doc-biblioref">Park et al. 2020</a>)</span>.</p>
<p>Unsupervised clustering has no such external anchor. It is built only from a feature space that may encode scanner, protocol and manufacturer effects. If technical differences explain more of the structure than tumour biology does, the algorithm recovers the hardware-defined partition first — and silhouette scores and bootstrap stability then test the reproducibility of that partition rather than its biological validity <span class="citation" data-cites="handl2005">(<a href="#ref-handl2005" role="doc-biblioref">Handl et al. 2005</a>)</span>.</p>
<blockquote class="blockquote">
<p>Mathematical reproducibility can be mistaken for biological validity.</p>
</blockquote>
</section>
<section id="technical-variance-in-radiomics" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="technical-variance-in-radiomics"><span class="header-section-number">2.3</span> Technical variance in radiomics</h2>
<p>The literature on acquisition effects is extensive: features such as voxel size and gray-level discretization make many descriptors non-reproducible under acquisition variation <span class="citation" data-cites="berenguer2018 mackin2015 duron2019 leijenaar2015">(<a href="#ref-berenguer2018" role="doc-biblioref">Berenguer et al. 2018</a>; <a href="#ref-mackin2015" role="doc-biblioref">Mackin et al. 2015</a>; <a href="#ref-duron2019" role="doc-biblioref">Duron et al. 2019</a>; <a href="#ref-leijenaar2015" role="doc-biblioref">Leijenaar et al. 2015</a>)</span>. This is a large part of why radiomics has not fully transitioned into clinical workflow, despite standardization efforts such as the Image Biomarker Standardisation Initiative <span class="citation" data-cites="zwanenburg2020 traverso2018">(<a href="#ref-zwanenburg2020" role="doc-biblioref"><span class="nocase">Zwanenburg et al.</span> 2020</a>; <a href="#ref-traverso2018" role="doc-biblioref">Traverso et al. 2018</a>)</span>. MRI compounds the problem, since protocols, coils and pulse sequences differ across vendors <span class="citation" data-cites="nyul1999">(<a href="#ref-nyul1999" role="doc-biblioref">Nyúl and Udupa 1999</a>)</span>.</p>
<p>The most direct proof of concept comes from multi-vendor breast-MRI radiomics: non-biological features predicted scanner platform and field strength with AUCs of 0.91–1.00, while the same pipeline predicted tumour biology only modestly (AUC 0.673 for pathological nodal status) without clinical variables <span class="citation" data-cites="doran2021">(<a href="#ref-doran2021" role="doc-biblioref"><span class="nocase">Doran et al.</span> 2021</a>)</span>. Radiomic features can encode strong technical signal, and that signal competes with tumour biology inside the same feature space.</p>
</section>
<section id="harmonization-and-its-limits" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="harmonization-and-its-limits"><span class="header-section-number">2.4</span> Harmonization and its limits</h2>
<p>Feature-level harmonization is the standard remedy. ComBat, developed for batch effects in gene expression, was extended to neuroimaging and radiomics to remove scanner, site and protocol effects while retaining biological information <span class="citation" data-cites="johnson2007 fortin2018">(<a href="#ref-johnson2007" role="doc-biblioref">Johnson et al. 2007</a>; <a href="#ref-fortin2018" role="doc-biblioref">Fortin et al. 2018</a>)</span>. In radiomics it has been used almost exclusively to improve cross-site comparability or the transportability of supervised models <span class="citation" data-cites="leithner2022">(<a href="#ref-leithner2022" role="doc-biblioref">Leithner et al. 2022</a>)</span>, and it reduces batch effects and improves performance across PET, MRI and multi-centre settings <span class="citation" data-cites="daano2020">(<a href="#ref-daano2020" role="doc-biblioref">Da-Ano et al. 2020</a>)</span>.</p>
<p>But those evaluations assume the endpoint is what matters. That is the right frame for supervised prediction and the wrong one for unsupervised phenotypes, where the question is what happens to the <em>patient partition</em> after harmonization. If a cluster reflects manufacturer variance more than tumour biology, ComBat can leave the mathematical stability intact while substituting a different partition that also passes validation. Standard metrics raise no alarm, because the mathematical properties have not changed — only the meaning has <span class="citation" data-cites="lozano2024">(<a href="#ref-lozano2024" role="doc-biblioref">Lozano-Montoya and Jimenez-Pastor 2024</a>)</span>.</p>
</section>
<section id="the-validation-gap" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="the-validation-gap"><span class="header-section-number">2.5</span> The validation gap</h2>
<p>For prediction modelling it is accepted that internal performance is not enough: claims must face robustness checks, stress tests and external validation before generalizability is granted <span class="citation" data-cites="collins2015">(<a href="#ref-collins2015" role="doc-biblioref">Collins et al. 2015</a>)</span>. A phenotype claim should likewise be exposed to tests designed to <em>disprove</em> its biological interpretation. The question is not whether a reproducible cluster exists, but whether the same biological claim survives when technical variance is explicitly tested — whether clusters map more strongly to manufacturer than to subtype, whether the leading principal components are acquisition-dominated, whether identity and prognostic relevance survive residualization and ComBat, and whether what remains meets minimum biomarker criteria <span class="citation" data-cites="lu2021">(<a href="#ref-lu2021" role="doc-biblioref">Lu et al. 2021</a>)</span>.</p>
<p>The argument is not that unsupervised radiomic discovery is invalid. It is that cluster stability is not equivalent to biological validity, particularly in multi-vendor data. The literature already establishes that feature space can be acquisition-dominated and that harmonization can mitigate it <span class="citation" data-cites="yamamoto2012 traverso2018 daano2020">(<a href="#ref-yamamoto2012" role="doc-biblioref">Yamamoto et al. 2012</a>; <a href="#ref-traverso2018" role="doc-biblioref">Traverso et al. 2018</a>; <a href="#ref-daano2020" role="doc-biblioref">Da-Ano et al. 2020</a>)</span>; what is missing is an end-to-end falsification pipeline that tests whether a stable cluster retains its identity and interpretation once known acquisition effects are adjusted for.</p>
</section>
</section>
<section id="materials-and-methods" class="level1 page-columns page-full" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Materials and methods</h1>
<section id="data" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h2>
<p>We use a 922-patient breast-MRI dataset with 529 quantitative MRI-derived radiomic features <span class="citation" data-cites="saha2021data saha2018">(<a href="#ref-saha2021data" role="doc-biblioref">Saha et al. 2021</a>, <a href="#ref-saha2018" role="doc-biblioref">2018</a>)</span>. Variables were retained if they had &lt;5% missingness and ≥2 unique values; under these criteria no features were removed. Missing values were median-imputed and all features standardized to zero mean before PCA, clustering, harmonization and survival modelling.</p>
<p>Z-scoring is not cosmetic here. The feature set mixes enhancement kinetics, peak enhancement, signal-enhancement ratio and texture statistics, all reported on different natural scales; without standardization, variance-driven methods such as PCA and k-means would be led by numerical scale rather than data structure.</p>
<div class="cell" data-execution_count="3">
<div id="tbl-preprocessing" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="3">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-preprocessing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Radiomic matrix and preprocessing. No feature was lost to the filters — the 529-column matrix that enters PCA is the one the source data provides.
</figcaption>
<div aria-describedby="tbl-preprocessing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="3">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Step</th>
<th style="text-align: right;">Patients</th>
<th style="text-align: right;">Features</th>
<th style="text-align: left;">Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Raw imaging matrix</td>
<td style="text-align: right;">922</td>
<td style="text-align: right;">529</td>
<td style="text-align: left;">Numeric MRI-derived radiomic features</td>
</tr>
<tr class="even">
<td style="text-align: left;">Missingness filter (&lt;5%)</td>
<td style="text-align: right;">922</td>
<td style="text-align: right;">529</td>
<td style="text-align: left;">No variable exceeded the threshold</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Unique-value filter (≥2)</td>
<td style="text-align: right;">922</td>
<td style="text-align: right;">529</td>
<td style="text-align: left;">No constant variables present</td>
</tr>
<tr class="even">
<td style="text-align: left;">Median imputation</td>
<td style="text-align: right;">922</td>
<td style="text-align: right;">529</td>
<td style="text-align: left;">Applied within retained variables</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Z-score standardization</td>
<td style="text-align: right;">922</td>
<td style="text-align: right;">529</td>
<td style="text-align: left;">Zero mean, unit variance per feature</td>
</tr>
<tr class="even">
<td style="text-align: left;">Matrix entering PCA</td>
<td style="text-align: right;">922</td>
<td style="text-align: right;">529</td>
<td style="text-align: left;">Input to PCA, k-means, harmonization</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="standard-phenotype-discovery" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="standard-phenotype-discovery"><span class="header-section-number">3.2</span> Standard phenotype discovery</h2>
<p>PCA was applied to the standardized matrix and the leading components retained for visualization and clustering. Clustering used k-means across candidate <em>k</em>, with internal validity summarized by silhouette score, Calinski–Harabasz index and Davies–Bouldin index. Bootstrap stability was assessed by 20 repetitions of 80% subsampling and reported as the adjusted Rand index (ARI). Feature differences between clusters were assessed with Welch tests and Benjamini–Hochberg correction. This entire stage was run on the raw partition, to establish that it has a coherent imaging interpretation <em>before</em> any technical challenge is applied.</p>
</section>
<section id="falsification-chain-and-technical-adjudication" class="level2 page-columns page-full" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="falsification-chain-and-technical-adjudication"><span class="header-section-number">3.3</span> Falsification chain and technical adjudication</h2>
<p>Four steps. Technical enrichment was measured by comparing cluster labels and PC structure against acquisition variables. Phenotype discovery was then repeated after manufacturer residualization and after ComBat harmonization. Partition identity was quantified by comparing harmonized labels with raw labels using ARI. Finally, clinical interpretability was retested after manufacturer adjustment.</p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">Steps 2 and 3 are the ones missing from conventional practice. Step 3 in particular has no standard reporting slot, which is why partition identity goes unreported even when it has collapsed.</span></div></div>
</section>
<section id="clinical-and-biomarker-evaluation" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="clinical-and-biomarker-evaluation"><span class="header-section-number">3.4</span> Clinical and biomarker evaluation</h2>
<p>The top screen was recurrence-free survival in the HR+/HER2+ subgroup, where the raw phenotype showed its strongest survival split, using Kaplan–Meier curves, the log-rank test and Cox proportional-hazards models. The cluster effect was then re-estimated with manufacturer in the model, to ask whether it remains interpretable after technical adjustment. The post-harmonization structure was finally assessed against prespecified biomarker criteria. Those criteria are deliberately minimal: they are identification thresholds, not confirmation of biological validity.</p>
</section>
</section>
<section id="results" class="level1 page-columns page-full" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Results</h1>
<section id="sec-km1" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="sec-km1"><span class="header-section-number">4.1</span> A standard workflow produces a plausible but fragile discovery</h2>
<p>At first glance the output reads as a phenotype discovery.</p>
<p>The top ten principal components explain 57.9% of the variance, with PC1, PC2 and PC3 at 15.5%, 9.6% and 7.8% (<a href="#tbl-variance" class="quarto-xref">Table&nbsp;3</a>). The scree plot and the PC1–PC2 projection (<a href="#fig-scree" class="quarto-xref">Figure&nbsp;2</a>, <a href="#fig-pca" class="quarto-xref">Figure&nbsp;7</a>) show a continuum rather than separated masses: any clustering here draws a gradient boundary, not a natural one.</p>
<div id="cell-fig-scree" class="cell" data-execution_count="4">
<div id="fig-scree" class="cell-output cell-output-display cell-output-markdown quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="4">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="light-content">
<p><a href="figures/fig-scree-light.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;2: Scree plot and cumulative variance for the leading 20 principal components."><img src="figures/fig-scree-light.svg" class="img-fluid figure-img" alt="Bar chart of variance explained per principal component with a cumulative curve; the decline is smooth, with no elbow."></a></p>
</div>
<div class="dark-content">
<p><a href="figures/fig-scree-dark.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;2: Scree plot and cumulative variance for the leading 20 principal components."><img src="figures/fig-scree-dark.svg" class="img-fluid figure-img" alt="Bar chart of variance explained per principal component with a cumulative curve; the decline is smooth, with no elbow."></a></p>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Scree plot and cumulative variance for the leading 20 principal components.
</figcaption>
</figure>
</div>
</div>
<div class="cell" data-execution_count="5">
<div id="tbl-variance" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="5">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-variance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Variance explained by the leading principal components.
</figcaption>
<div aria-describedby="tbl-variance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="5">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Principal component</th>
<th style="text-align: right;">Variance explained</th>
<th style="text-align: right;">Cumulative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PC1</td>
<td style="text-align: right;">15.49%</td>
<td style="text-align: right;">15.5%</td>
</tr>
<tr class="even">
<td style="text-align: left;">PC2</td>
<td style="text-align: right;">9.58%</td>
<td style="text-align: right;">25.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PC3</td>
<td style="text-align: right;">7.75%</td>
<td style="text-align: right;">32.8%</td>
</tr>
<tr class="even">
<td style="text-align: left;">PC4</td>
<td style="text-align: right;">5.32%</td>
<td style="text-align: right;">38.2%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PC5</td>
<td style="text-align: right;">4.95%</td>
<td style="text-align: right;">43.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">PC6</td>
<td style="text-align: right;">3.74%</td>
<td style="text-align: right;">46.8%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PC7</td>
<td style="text-align: right;">3.54%</td>
<td style="text-align: right;">50.4%</td>
</tr>
<tr class="even">
<td style="text-align: left;">PC8</td>
<td style="text-align: right;">2.96%</td>
<td style="text-align: right;">53.3%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PC9</td>
<td style="text-align: right;">2.41%</td>
<td style="text-align: right;">55.8%</td>
</tr>
<tr class="even">
<td style="text-align: left;">PC10</td>
<td style="text-align: right;">2.15%</td>
<td style="text-align: right;">57.9%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>k-means selected <em>k</em> = 2 on the metrics that are conventionally reported: the highest silhouette score (0.196) and the highest Calinski–Harabasz index (200.9), both declining as <em>k</em> grows (<a href="#fig-validity" class="quarto-xref">Figure&nbsp;3</a>). Davies–Bouldin does not agree — <em>k</em> = 2 is its worst solution — which is itself worth noticing, since the selection rests on two of three metrics and the disagreement is rarely reported.</p>
<div id="cell-fig-validity" class="cell" data-execution_count="6">
<div id="fig-validity" class="cell-output cell-output-display cell-output-markdown quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="6">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-validity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="light-content">
<p><a href="figures/fig-validity-light.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;3: Internal cluster validity across candidate k. Two of the three metrics select k = 2; the third selects against it."><img src="figures/fig-validity-light.svg" class="img-fluid figure-img" alt="Three bar panels of silhouette, Calinski-Harabasz and Davies-Bouldin scores across k from 2 to 6."></a></p>
</div>
<div class="dark-content">
<p><a href="figures/fig-validity-dark.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;3: Internal cluster validity across candidate k. Two of the three metrics select k = 2; the third selects against it."><img src="figures/fig-validity-dark.svg" class="img-fluid figure-img" alt="Three bar panels of silhouette, Calinski-Harabasz and Davies-Bouldin scores across k from 2 to 6."></a></p>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-validity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Internal cluster validity across candidate k. Two of the three metrics select k = 2; the third selects against it.
</figcaption>
</figure>
</div>
</div>
<p>Bootstrap stability was strong: the raw <em>k</em> = 2 partition attained a mean ARI of 0.893 (SD 0.084) across 20 subsamples (<a href="#fig-bootstrap" class="quarto-xref">Figure&nbsp;9</a>). By the standards usually applied, this is where a phenotype paper would stop.</p>
<p>Feature-level inspection then supplied a biologically plausible reading. The top-ranked separating variables are dominated by signal-enhancement ratio (SER), peak enhancement (PE), entropy, homogeneity and related enhancement-texture descriptors, with |Cohen’s <em>d</em>| above 2.2 for the leading SER entropy and sum-entropy features (<a href="#fig-features" class="quarto-xref">Figure&nbsp;4</a>, <a href="#tbl-features" class="quarto-xref">Table&nbsp;4</a>). The phenotype looks <em>vascularity-like</em>: one group with more spatially heterogeneous enhancement, the other more homogeneous. Whether that has a genuine biological basis is, for our purposes, beside the point — what matters is how readily the interpretation attaches.</p>
<div id="cell-fig-features" class="cell" data-execution_count="7">
<div id="fig-features" class="cell-output cell-output-display cell-output-markdown quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="7">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-features-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="light-content">
<p><a href="figures/fig-features-light.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure&nbsp;4: The 14 strongest cluster-separating features, as cluster means in z-scored units with Cohen’s d."><img src="figures/fig-features-light.svg" class="img-fluid figure-img" alt="Dumbbell chart of the top separating radiomic features, showing cluster 0 and cluster 1 means far apart."></a></p>
</div>
<div class="dark-content">
<p><a href="figures/fig-features-dark.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure&nbsp;4: The 14 strongest cluster-separating features, as cluster means in z-scored units with Cohen’s d."><img src="figures/fig-features-dark.svg" class="img-fluid figure-img" alt="Dumbbell chart of the top separating radiomic features, showing cluster 0 and cluster 1 means far apart."></a></p>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-features-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: The 14 strongest cluster-separating features, as cluster means in z-scored units with Cohen’s d.
</figcaption>
</figure>
</div>
</div>
<div class="cell" data-execution_count="8">
<div id="tbl-features" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="8">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-features-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Top raw cluster-separating radiomic features (Welch tests, Benjamini–Hochberg corrected).
</figcaption>
<div aria-describedby="tbl-features-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="8">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Feature</th>
<th style="text-align: right;">Mean C0</th>
<th style="text-align: right;">Mean C1</th>
<th style="text-align: right;">Δ (C1−C0)</th>
<th style="text-align: right;">Cohen’s d</th>
<th style="text-align: right;">q-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SER map Entropy tissue T1</td>
<td style="text-align: right;">-0.552</td>
<td style="text-align: right;">0.964</td>
<td style="text-align: right;">+1.516</td>
<td style="text-align: right;">2.21</td>
<td style="text-align: right;">1.1 × 10⁻¹⁰⁰</td>
</tr>
<tr class="even">
<td style="text-align: left;">SER map sum entropy tissue T1</td>
<td style="text-align: right;">-0.552</td>
<td style="text-align: right;">0.963</td>
<td style="text-align: right;">+1.515</td>
<td style="text-align: right;">2.21</td>
<td style="text-align: right;">2.7 × 10⁻¹⁰⁹</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SER map std dev tissue T1</td>
<td style="text-align: right;">0.550</td>
<td style="text-align: right;">-0.960</td>
<td style="text-align: right;">-1.510</td>
<td style="text-align: right;">-2.20</td>
<td style="text-align: right;">2.5 × 10⁻¹⁶⁴</td>
</tr>
<tr class="even">
<td style="text-align: left;">SER map difference entropy tissue T1</td>
<td style="text-align: right;">-0.546</td>
<td style="text-align: right;">0.953</td>
<td style="text-align: right;">+1.499</td>
<td style="text-align: right;">2.16</td>
<td style="text-align: right;">1.2 × 10⁻¹⁰³</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SER map Homogeneity2 tissue T1</td>
<td style="text-align: right;">0.540</td>
<td style="text-align: right;">-0.942</td>
<td style="text-align: right;">-1.483</td>
<td style="text-align: right;">-2.11</td>
<td style="text-align: right;">2.5 × 10⁻⁹⁵</td>
</tr>
<tr class="even">
<td style="text-align: left;">SER map Homogeneity1 tissue T1</td>
<td style="text-align: right;">0.539</td>
<td style="text-align: right;">-0.940</td>
<td style="text-align: right;">-1.479</td>
<td style="text-align: right;">-2.10</td>
<td style="text-align: right;">1.7 × 10⁻⁹⁷</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SER map inverse difference is homom tissue T1</td>
<td style="text-align: right;">0.539</td>
<td style="text-align: right;">-0.940</td>
<td style="text-align: right;">-1.479</td>
<td style="text-align: right;">-2.10</td>
<td style="text-align: right;">1.7 × 10⁻⁹⁷</td>
</tr>
<tr class="even">
<td style="text-align: left;">PE map std dev tissue T1</td>
<td style="text-align: right;">0.532</td>
<td style="text-align: right;">-0.927</td>
<td style="text-align: right;">-1.459</td>
<td style="text-align: right;">-2.05</td>
<td style="text-align: right;">1.7 × 10⁻¹⁶⁴</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Finally, the raw partition looked prognostically meaningful in HR+/HER2+ disease. Of 101 patients with usable follow-up, Cluster 0 had 55 patients and 2 recurrences; Cluster 1 had 46 patients and 8. Kaplan–Meier curves separate visibly (<a href="#fig-km" class="quarto-xref">Figure&nbsp;5</a>), the log-rank test is significant (p = 0.010), and an unadjusted Cox model gives HR = 4.76 for Cluster 1 versus Cluster 0 (95% CI 1.22–18.61; p = 0.025) (<a href="#tbl-cox-unadjusted" class="quarto-xref">Table&nbsp;5</a>).</p>
<div id="cell-fig-km" class="cell" data-execution_count="9">
<div id="fig-km" class="cell-output cell-output-display cell-output-markdown quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="9">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-km-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="light-content">
<p><a href="figures/fig-km-light.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figure&nbsp;5: Recurrence-free survival in HR+/HER2+ patients by raw radiomic cluster, with 95% confidence bands and numbers at risk."><img src="figures/fig-km-light.svg" class="img-fluid figure-img" alt="Kaplan-Meier curves for two clusters, separating after about 1.5 years, with a numbers-at-risk table."></a></p>
</div>
<div class="dark-content">
<p><a href="figures/fig-km-dark.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Figure&nbsp;5: Recurrence-free survival in HR+/HER2+ patients by raw radiomic cluster, with 95% confidence bands and numbers at risk."><img src="figures/fig-km-dark.svg" class="img-fluid figure-img" alt="Kaplan-Meier curves for two clusters, separating after about 1.5 years, with a numbers-at-risk table."></a></p>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-km-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Recurrence-free survival in HR+/HER2+ patients by raw radiomic cluster, with 95% confidence bands and numbers at risk.
</figcaption>
</figure>
</div>
</div>
<div class="cell" data-execution_count="10">
<div id="tbl-cox-unadjusted" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="10">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cox-unadjusted-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: The unadjusted HR+/HER2+ recurrence-free survival signal by raw radiomic cluster.
</figcaption>
<div aria-describedby="tbl-cox-unadjusted-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="10">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Analysis</th>
<th style="text-align: left;">Estimate</th>
<th style="text-align: left;">Interval / rate</th>
<th style="text-align: right;">p-value</th>
<th style="text-align: left;">Reading</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cluster 0</td>
<td style="text-align: left;">55 patients, 2 events</td>
<td style="text-align: left;">3.6%</td>
<td style="text-align: right;">—</td>
<td style="text-align: left;">Lower unadjusted recurrence burden</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cluster 1</td>
<td style="text-align: left;">46 patients, 8 events</td>
<td style="text-align: left;">17.4%</td>
<td style="text-align: right;">—</td>
<td style="text-align: left;">Higher unadjusted recurrence burden</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Log-rank test</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">—</td>
<td style="text-align: right;">0.010</td>
<td style="text-align: left;">Curves separate</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cox, cluster only</td>
<td style="text-align: left;">HR = 4.76</td>
<td style="text-align: left;">95% CI 1.22–18.61</td>
<td style="text-align: right;">0.025</td>
<td style="text-align: left;">Significant before technical adjustment</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>In ordinary circumstances this is a reproducible vascularity-like prognostic phenotype. Here it is the counterexample the rest of the paper dismantles.</p>
</section>
<section id="sec-km2" class="level2 page-columns page-full" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="sec-km2"><span class="header-section-number">4.2</span> The phenotype is acquisition-dominated, not subtype-defined</h2>
<p>Once acquisition variables enter, the reading changes. The raw cluster is associated with manufacturer at p = 8.0 × 10⁻¹⁰⁴, and with neither molecular subtype (p = 0.146) nor recurrence (p = 0.766) (<a href="#tbl-association" class="quarto-xref">Table&nbsp;6</a>). The contingency is not subtle: Cluster 0 is 93% GE, Cluster 1 is 76% Siemens (<a href="#fig-composition" class="quarto-xref">Figure&nbsp;6</a>, <a href="#tbl-composition" class="quarto-xref">Table&nbsp;7</a>).</p>
<div class="cell" data-execution_count="11">
<div id="tbl-association" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="11">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-association-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Association of raw cluster assignment with clinical and technical variables (χ² tests).
</figcaption>
<div aria-describedby="tbl-association-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="11">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">p-value</th>
<th style="text-align: left;">Reading</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Manufacturer</td>
<td style="text-align: right;">8.0 × 10⁻¹⁰⁴</td>
<td style="text-align: left;">Strong association with cluster assignment</td>
</tr>
<tr class="even">
<td style="text-align: left;">Molecular Subtype</td>
<td style="text-align: right;">0.146</td>
<td style="text-align: left;">No significant association</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Recurrence</td>
<td style="text-align: right;">0.766</td>
<td style="text-align: left;">No significant association</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div id="cell-fig-composition" class="cell" data-execution_count="12">
<div id="fig-composition" class="cell-output cell-output-display cell-output-markdown quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="12">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-composition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="light-content">
<p><a href="figures/fig-composition-light.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-9" title="Figure&nbsp;6: Manufacturer composition within each raw radiomic cluster."><img src="figures/fig-composition-light.svg" class="img-fluid figure-img" alt="Stacked horizontal bars: cluster 0 is 93% GE, cluster 1 is 76% Siemens."></a></p>
</div>
<div class="dark-content">
<p><a href="figures/fig-composition-dark.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-10" title="Figure&nbsp;6: Manufacturer composition within each raw radiomic cluster."><img src="figures/fig-composition-dark.svg" class="img-fluid figure-img" alt="Stacked horizontal bars: cluster 0 is 93% GE, cluster 1 is 76% Siemens."></a></p>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-composition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Manufacturer composition within each raw radiomic cluster.
</figcaption>
</figure>
</div>
</div>
<div class="cell" data-execution_count="13">
<div id="tbl-composition" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="13">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-composition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Raw cluster assignment by MRI manufacturer.
</figcaption>
<div aria-describedby="tbl-composition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="13">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Cluster</th>
<th style="text-align: right;">GE</th>
<th style="text-align: right;">Siemens</th>
<th style="text-align: right;">Reading</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cluster 0</td>
<td style="text-align: right;">547</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">Predominantly GE</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cluster 1</td>
<td style="text-align: right;">81</td>
<td style="text-align: right;">255</td>
<td style="text-align: right;">Predominantly Siemens</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The clearest way to see it is to recolour the same projection. Below is one PC1–PC2 scatter — the same 922 points in the same positions — coloured first by the cluster the algorithm discovered, then by the scanner that acquired the image. Switch between them:</p>
<div id="fig-pca" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pca-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<style>
.pca-toggle { margin: 1.6rem 0 0.4rem; }
.pca-toggle > input { position: absolute; opacity: 0; pointer-events: none; }
.pca-tabs { display: flex; gap: 0.4rem; margin-bottom: 0.9rem; flex-wrap: wrap; }
.pca-tabs label {
  font-size: 0.8rem; font-weight: 500; letter-spacing: 0.01em;
  padding: 0.34rem 0.8rem; border: 1px solid var(--bs-border-color, #e3e1dc);
  border-radius: 999px; cursor: pointer; user-select: none;
  color: var(--bs-secondary-color, #5c6672);
  transition: border-color 150ms ease, color 150ms ease, background 150ms ease;
}
.pca-tabs label:hover { color: var(--bs-link-color, #8a2f2f); }
.pca-stack > .view { display: none; }
#pca-view-cluster:checked ~ .pca-stack > .v-cluster,
#pca-view-vendor:checked  ~ .pca-stack > .v-vendor { display: block; }
#pca-view-cluster:checked ~ .pca-tabs label[for="pca-view-cluster"],
#pca-view-vendor:checked  ~ .pca-tabs label[for="pca-view-vendor"] {
  border-color: var(--bs-link-color, #8a2f2f);
  color: var(--bs-link-color, #8a2f2f);
}
.pca-stack img { width: 100%; height: auto; }
.pca-note { font-size: 0.82rem; color: var(--bs-secondary-color, #5c6672); margin-top: 0.2rem; }
</style>
<div class="pca-toggle">
  <input type="radio" name="pca-view" id="pca-view-cluster" checked="">
  <input type="radio" name="pca-view" id="pca-view-vendor">
  <div class="pca-tabs">
    <label for="pca-view-cluster">Colour by radiomic cluster</label>
    <label for="pca-view-vendor">Colour by scanner manufacturer</label>
  </div>
  <div class="pca-stack">
    <div class="view v-cluster">
      <div class="light-content"><img src="figures/fig-pca-by-cluster-light.svg" alt="PC1-PC2 scatter coloured by radiomic cluster" class="figure-img"></div>
      <div class="dark-content"><img src="figures/fig-pca-by-cluster-dark.svg" alt="PC1-PC2 scatter coloured by radiomic cluster" class="figure-img"></div>
    </div>
    <div class="view v-vendor">
      <div class="light-content"><img src="figures/fig-pca-by-vendor-light.svg" alt="PC1-PC2 scatter coloured by scanner manufacturer" class="figure-img"></div>
      <div class="dark-content"><img src="figures/fig-pca-by-vendor-dark.svg" alt="PC1-PC2 scatter coloured by scanner manufacturer" class="figure-img"></div>
    </div>
  </div>
  <p class="pca-note">Same points, same axes. Only the colouring changes.</p>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pca-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Raw PCA space coloured by radiomic cluster and by manufacturer. The clustering algorithm partitioned the cohort by the machine that acquired the image.
</figcaption>
</figure>
</div>
<p>Looking into PC1 directly makes the mechanism explicit. TR, TE, the acquisition matrix and manufacturer all track PC1 far more closely than molecular subtype does, which stays below 0.01 across the leading components (<a href="#fig-eta2" class="quarto-xref">Figure&nbsp;8</a>, <a href="#tbl-eta2" class="quarto-xref">Table&nbsp;8</a>).</p>
<div id="cell-fig-eta2" class="cell" data-execution_count="15">
<div id="fig-eta2" class="cell-output cell-output-display cell-output-markdown quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="15">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-eta2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="light-content">
<p><a href="figures/fig-eta2-light.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-11" title="Figure&nbsp;8: Share of PC1 variance explained by acquisition and biological variables."><img src="figures/fig-eta2-light.svg" class="img-fluid figure-img" alt="Lollipop chart: acquisition variables explain 0.49-0.76 of PC1 variance; biological variables explain under 0.01."></a></p>
</div>
<div class="dark-content">
<p><a href="figures/fig-eta2-dark.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-12" title="Figure&nbsp;8: Share of PC1 variance explained by acquisition and biological variables."><img src="figures/fig-eta2-dark.svg" class="img-fluid figure-img" alt="Lollipop chart: acquisition variables explain 0.49-0.76 of PC1 variance; biological variables explain under 0.01."></a></p>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-eta2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Share of PC1 variance explained by acquisition and biological variables.
</figcaption>
</figure>
</div>
</div>
<div class="cell" data-execution_count="16">
<div id="tbl-eta2" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="16">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-eta2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: Acquisition-variable dominance on the leading radiomic axes (η², share of component variance explained).
</figcaption>
<div aria-describedby="tbl-eta2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="16">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Kind</th>
<th style="text-align: right;">PC1</th>
<th style="text-align: right;">PC2</th>
<th style="text-align: right;">PC3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">TR (repetition time)</td>
<td style="text-align: left;">Technical</td>
<td style="text-align: right;">0.755</td>
<td style="text-align: right;">0.567</td>
<td style="text-align: right;">0.421</td>
</tr>
<tr class="even">
<td style="text-align: left;">TE (echo time)</td>
<td style="text-align: left;">Technical</td>
<td style="text-align: right;">0.632</td>
<td style="text-align: right;">0.355</td>
<td style="text-align: right;">0.198</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Acquisition matrix</td>
<td style="text-align: left;">Technical</td>
<td style="text-align: right;">0.567</td>
<td style="text-align: right;">0.286</td>
<td style="text-align: right;">0.047</td>
</tr>
<tr class="even">
<td style="text-align: left;">Manufacturer</td>
<td style="text-align: left;">Technical</td>
<td style="text-align: right;">0.489</td>
<td style="text-align: right;">0.119</td>
<td style="text-align: right;">0.011</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Field strength</td>
<td style="text-align: left;">Technical</td>
<td style="text-align: right;">0.093</td>
<td style="text-align: right;">0.036</td>
<td style="text-align: right;">0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Slice thickness</td>
<td style="text-align: left;">Technical</td>
<td style="text-align: right;">0.075</td>
<td style="text-align: right;">0.130</td>
<td style="text-align: right;">0.018</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Molecular subtype</td>
<td style="text-align: left;">Biological</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">0.035</td>
</tr>
<tr class="even">
<td style="text-align: left;">Recurrence</td>
<td style="text-align: left;">Biological</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.022</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">η² is inflated for a continuous acquisition parameter when each distinct observed value forms its own group, as TR does here (337 distinct values). Grouped into 20 quantile bins TR still explains 0.56 of PC1, and a purely linear fit gives R² = 0.34. The ordering does not change: acquisition first, biology nowhere. The full sensitivity table is written to <code>_data/acquisition_eta2_sensitivity.csv</code>.</span></div></div>
<p>This is the stability trap in its plainest form. The partition is not noisy — it is stable, because the scanner-domain structure it recovers is itself perfectly reproducible. High bootstrap ARI is evidence that the technical signal is consistent, not that the biology is real.</p>
</section>
<section id="sec-km3" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="sec-km3"><span class="header-section-number">4.3</span> Harmonization preserves stability and destroys identity</h2>
<p>Residualization and ComBat both remove the manufacturer association — and take the phenotype with them.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Raw</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Manufacturer residualized</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false" href="">ComBat harmonized</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div id="cell-cond-raw" class="cell" data-execution_count="17">
<div id="cond-raw" class="cell-output cell-output-display cell-output-markdown" data-execution_count="17">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Measure</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mean bootstrap ARI</td>
<td style="text-align: right;">0.893 (SD 0.084)</td>
</tr>
<tr class="even">
<td style="text-align: left;">ARI vs raw labels</td>
<td style="text-align: right;">1.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Manufacturer association</td>
<td style="text-align: right;">8.0 × 10⁻¹⁰⁴</td>
</tr>
<tr class="even">
<td style="text-align: left;">Molecular subtype association</td>
<td style="text-align: right;">0.146</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Recurrence association</td>
<td style="text-align: right;">0.766</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The baseline. Stable, and defined by the scanner.</p>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div id="cell-cond-resid" class="cell" data-execution_count="18">
<div id="cond-resid" class="cell-output cell-output-display cell-output-markdown" data-execution_count="18">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Measure</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mean bootstrap ARI</td>
<td style="text-align: right;">0.919 (SD 0.047)</td>
</tr>
<tr class="even">
<td style="text-align: left;">ARI vs raw labels</td>
<td style="text-align: right;">0.056</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Manufacturer association</td>
<td style="text-align: right;">0.530</td>
</tr>
<tr class="even">
<td style="text-align: left;">Molecular subtype association</td>
<td style="text-align: right;">0.717</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Recurrence association</td>
<td style="text-align: right;">0.075</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Manufacturer dependence is gone. So is the partition: an ARI of 0.056 against the raw labels means the two solutions agree at close to chance.</p>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<div id="cell-cond-combat" class="cell" data-execution_count="19">
<div id="cond-combat" class="cell-output cell-output-display cell-output-markdown" data-execution_count="19">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Measure</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mean bootstrap ARI</td>
<td style="text-align: right;">0.903 (SD 0.058)</td>
</tr>
<tr class="even">
<td style="text-align: left;">ARI vs raw labels</td>
<td style="text-align: right;">0.065</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Manufacturer association</td>
<td style="text-align: right;">0.177</td>
</tr>
<tr class="even">
<td style="text-align: left;">Molecular subtype association</td>
<td style="text-align: right;">0.809</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Recurrence association</td>
<td style="text-align: right;">0.056</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The same story by a different route. Clusterability survives; identity does not.</p>
</div>
</div>
</div>
<p>The ARI between residualized and raw labels was 0.056; between ComBat and raw, 0.065. Both indicate near-total loss of partition identity. What did <em>not</em> degrade is clusterability: both spaces still split into internally consistent two-cluster solutions, with mean bootstrap ARI of 0.919 and 0.903 respectively (<a href="#fig-bootstrap" class="quarto-xref">Figure&nbsp;9</a>, <a href="#tbl-stability" class="quarto-xref">Table&nbsp;9</a>).</p>
<div id="cell-fig-bootstrap" class="cell" data-execution_count="20">
<div id="fig-bootstrap" class="cell-output cell-output-display cell-output-markdown quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="20">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bootstrap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="light-content">
<p><a href="figures/fig-bootstrap-light.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-13" title="Figure&nbsp;9: Bootstrap stability across raw and harmonized conditions. Every condition passes."><img src="figures/fig-bootstrap-light.svg" class="img-fluid figure-img" alt="Dot-and-error-bar chart showing mean bootstrap ARI near 0.9 for all three conditions."></a></p>
</div>
<div class="dark-content">
<p><a href="figures/fig-bootstrap-dark.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-14" title="Figure&nbsp;9: Bootstrap stability across raw and harmonized conditions. Every condition passes."><img src="figures/fig-bootstrap-dark.svg" class="img-fluid figure-img" alt="Dot-and-error-bar chart showing mean bootstrap ARI near 0.9 for all three conditions."></a></p>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bootstrap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Bootstrap stability across raw and harmonized conditions. Every condition passes.
</figcaption>
</figure>
</div>
</div>
<p><a href="#fig-identity" class="quarto-xref">Figure&nbsp;10</a> makes the same point geometrically: the same patients, in the same projection, sorted into a partition that bears almost no relation to the original one.</p>
<div id="cell-fig-identity" class="cell" data-execution_count="21">
<div id="fig-identity" class="cell-output cell-output-display cell-output-markdown quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="21">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-identity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="light-content">
<p><a href="figures/fig-identity-scramble-light.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-15" title="Figure&nbsp;10: The same PCA space labelled by the raw partition and by the partition rediscovered after manufacturer residualization."><img src="figures/fig-identity-scramble-light.svg" class="img-fluid figure-img" alt="Two PCA scatterplots of the same points: the raw split is left-right, the residualized split is unrelated."></a></p>
</div>
<div class="dark-content">
<p><a href="figures/fig-identity-scramble-dark.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-16" title="Figure&nbsp;10: The same PCA space labelled by the raw partition and by the partition rediscovered after manufacturer residualization."><img src="figures/fig-identity-scramble-dark.svg" class="img-fluid figure-img" alt="Two PCA scatterplots of the same points: the raw split is left-right, the residualized split is unrelated."></a></p>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-identity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: The same PCA space labelled by the raw partition and by the partition rediscovered after manufacturer residualization.
</figcaption>
</figure>
</div>
</div>
<p>Plotting the two properties against each other separates concepts that are routinely conflated. Bootstrap stability asks whether a cluster solution can be <em>repeated</em> under resampling. Partition identity asks whether the <em>same patients</em> stay together after a technical adjustment. Here stability is preserved and identity is not — and a validation workflow that looks only at the first would certify this failure as a success.</p>
<div id="cell-fig-stability-identity" class="cell" data-execution_count="22">
<div id="fig-stability-identity" class="cell-output cell-output-display cell-output-markdown quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="22">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stability-identity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="light-content">
<p><a href="figures/fig-stability-identity-light.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-17" title="Figure&nbsp;11: Stability and identity are independent axes. Harmonization moves a phenotype down the identity axis without moving it along the stability axis at all."><img src="figures/fig-stability-identity-light.svg" class="img-fluid figure-img" alt="Scatter of mean bootstrap ARI against ARI versus raw labels; raw sits at the top, both harmonized conditions sit at the bottom despite equal stability."></a></p>
</div>
<div class="dark-content">
<p><a href="figures/fig-stability-identity-dark.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-18" title="Figure&nbsp;11: Stability and identity are independent axes. Harmonization moves a phenotype down the identity axis without moving it along the stability axis at all."><img src="figures/fig-stability-identity-dark.svg" class="img-fluid figure-img" alt="Scatter of mean bootstrap ARI against ARI versus raw labels; raw sits at the top, both harmonized conditions sit at the bottom despite equal stability."></a></p>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stability-identity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Stability and identity are independent axes. Harmonization moves a phenotype down the identity axis without moving it along the stability axis at all.
</figcaption>
</figure>
</div>
</div>
<div class="cell" data-execution_count="23">
<div id="tbl-stability" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="23">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-stability-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9: Stability versus identity across raw and harmonized conditions.
</figcaption>
<div aria-describedby="tbl-stability-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="23">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Condition</th>
<th style="text-align: right;">Mean bootstrap ARI</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">ARI vs raw labels</th>
<th style="text-align: left;">Reading</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Raw</td>
<td style="text-align: right;">0.893</td>
<td style="text-align: right;">0.084</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: left;">Stable baseline partition</td>
</tr>
<tr class="even">
<td style="text-align: left;">Manufacturer residualized</td>
<td style="text-align: right;">0.919</td>
<td style="text-align: right;">0.047</td>
<td style="text-align: right;">0.056</td>
<td style="text-align: left;">Stable, but nearly unrelated to the raw labels</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ComBat harmonized</td>
<td style="text-align: right;">0.903</td>
<td style="text-align: right;">0.058</td>
<td style="text-align: right;">0.065</td>
<td style="text-align: left;">Stable, but nearly unrelated to the raw labels</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="sec-km4" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="sec-km4"><span class="header-section-number">4.4</span> Neither the survival signal nor the residual structure supports a biomarker claim</h2>
<p>The HR+/HER2+ signal does not survive adjustment. Entered into a Cox model alongside manufacturer, the cluster hazard ratio falls from 4.76 to 2.48 and loses significance (95% CI 0.46–13.39; p = 0.291). Manufacturer is likewise non-significant in this subgroup (HR 2.99; p = 0.200) — but with 10 events there are not enough degrees of freedom to separate two correlated predictors, and the honest reading is that the design cannot distinguish them, not that neither matters (<a href="#tbl-cox-adjusted" class="quarto-xref">Table&nbsp;10</a>).</p>
<div class="cell" data-execution_count="24">
<div id="tbl-cox-adjusted" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="24">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cox-adjusted-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10: Manufacturer-adjusted Cox model in the HR+/HER2+ subgroup (10 events).
</figcaption>
<div aria-describedby="tbl-cox-adjusted-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="24">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Covariate</th>
<th style="text-align: right;">Coefficient</th>
<th style="text-align: right;">Hazard ratio</th>
<th style="text-align: left;">95% CI</th>
<th style="text-align: right;">p-value</th>
<th style="text-align: left;">Reading</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Raw cluster</td>
<td style="text-align: right;">0.908</td>
<td style="text-align: right;">2.48</td>
<td style="text-align: left;">0.46–13.39</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: left;">Attenuates and loses significance</td>
</tr>
<tr class="even">
<td style="text-align: left;">Manufacturer: Siemens vs GE</td>
<td style="text-align: right;">1.097</td>
<td style="text-align: right;">2.99</td>
<td style="text-align: left;">0.56–16.03</td>
<td style="text-align: right;">0.200</td>
<td style="text-align: left;">Non-significant, but collinear with cluster</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Structure does remain after the technical confounders are removed — but it is better described as a size-correlated residue than as an orthogonal discovery. The post-harmonization clusters are no longer detectably coupled to manufacturer, and associate most strongly with tumour bounding-box volume (p ≈ 10⁻²⁶). Against the prespecified criteria, that residue fails on every count (<a href="#tbl-biomarker" class="quarto-xref">Table&nbsp;11</a>): the recurrence association is weak, radiomic scores add nothing after clinical covariates, and the scores are not directionally consistent within vendors.</p>
<div class="cell" data-execution_count="25">
<div id="tbl-biomarker" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="25">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-biomarker-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11: Prespecified biomarker criteria applied to the post-harmonization residual structure.
</figcaption>
<div aria-describedby="tbl-biomarker-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="25">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Criterion</th>
<th style="text-align: left;">Observed result</th>
<th style="text-align: left;">Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Endpoint association</td>
<td style="text-align: left;">Cluster-level recurrence signals were weak and did not survive adjustment</td>
<td style="text-align: left;">❌ Not met</td>
</tr>
<tr class="even">
<td style="text-align: left;">Incremental predictive value</td>
<td style="text-align: left;">Radiomic/vascularity-augmented models did not improve on clinical covariates</td>
<td style="text-align: left;">❌ Not met</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Within-vendor consistency</td>
<td style="text-align: left;">Partition recovery differs sharply by vendor (ARI vs raw: 0.57 Siemens, 0.07 GE)</td>
<td style="text-align: left;">❌ Not met</td>
</tr>
<tr class="even">
<td style="text-align: left;">Independence from tumour burden</td>
<td style="text-align: left;">Strongest surviving association is with bounding-box volume (p ≈ 10⁻²⁶)</td>
<td style="text-align: left;">❌ Not met</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The conclusion is not that radiomic clustering is useless. It is that this apparent discovery must be downgraded to a false positive once it passes through acquisition-aware falsification.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>The minimum a phenotype claim should have to report
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>Multi-condition discovery.</strong> Re-run discovery after residualization and after ComBat, not only on raw features.</li>
<li><strong>Partition identity, not just stability.</strong> Report ARI of harmonized labels <em>against the original labels</em> — the number that collapsed here.</li>
<li><strong>Acquisition variance partitioning.</strong> Report η² or equivalent for acquisition <em>and</em> biological variables on the leading components.</li>
<li><strong>Harmonization sensitivity of clinical claims.</strong> Re-estimate every survival or outcome association after technical adjustment.</li>
<li><strong>Within-vendor sanity checks.</strong> Repeat discovery inside each vendor stratum; a biological phenotype should reappear in both.</li>
</ol>
</div>
</div>
</section>
</section>
<section id="discussion" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Discussion</h1>
<section id="the-negative-result-is-the-result" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="the-negative-result-is-the-result"><span class="header-section-number">5.1</span> The negative result is the result</h2>
<p>A radiomic partition can be internally stable, visually coherent and apparently prognostic while failing to represent a biological subgroup. Our two-group partition looked compelling on every metric that is conventionally reported: it was reproducible under resampling, carried a vascularity-associated profile, and suggested an HR+/HER2+ subgroup with elevated recurrence. Under inspection it aligned with scanner manufacturer and pulse sequence.</p>
<p>This is what the term <em>stability trap</em> is for. The raw phenotype was not meaningless noise — it was stable precisely because the acquisition signal is stable. The bootstrap scores were misleading only because they were read as evidence of biological truth. The accurate and much narrower inference is that the clustering algorithm recovered a strong, reproducible signal present in the radiomic feature matrix. The falsification chain then establishes that the dominant signal is technical. If there is a positive finding here, it is the invalidation of the phenotype claim, not the identification of a new phenotype.</p>
</section>
<section id="the-danger-is-in-the-language" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="the-danger-is-in-the-language"><span class="header-section-number">5.2</span> The danger is in the language</h2>
<p>Feature-wise, the separating variables made sense. SER entropy, SER homogeneity, PE variability, enhancement-volume ratios and wash-in/washout descriptors all suggest increased or decreased vascularity and perfusion. Enhancement-history descriptors are especially interpretable that way in breast DCE-MRI, where enhancement behaviour is already the central radiological finding.</p>
<p>That interpretability is what makes the trap dangerous: familiar vocabulary coats a technically induced partition. This is not an argument for avoiding biologically plausible language — enhancement features are not biologically meaningless. It is an argument that plausibility is not evidence. When the leading features are acquisition-sensitive, vascularity descriptors are a <em>hypothesis</em>, not a confirmation, and the profile should be stated as such — “these features are known to associate with vascularity, and the clusters separate on those features” — until the acquisition-aware checks are passed.</p>
</section>
<section id="stability-and-identity-are-separate-validation-targets" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="stability-and-identity-are-separate-validation-targets"><span class="header-section-number">5.3</span> Stability and identity are separate validation targets</h2>
<p>Harmonization is what makes the distinction visible. It did not destroy cluster stability; residualization and ComBat both produced perfectly stable two-cluster solutions. What changed is that the patients in those clusters were no longer the same patients.</p>
<p>In practice this means radiomic validation needs more than silhouette scores and bootstrap stability. A complete phenotype paper should report cluster preservation after acquisition correction, the technical-versus-biological dependencies of the leading components, the harmonization sensitivity of any clinical association, and the conformance of the post-harmonization structure to prespecified biomarker criteria.</p>
</section>
<section id="why-within-vendor-recovery-differs" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="why-within-vendor-recovery-differs"><span class="header-section-number">5.4</span> Why within-vendor recovery differs</h2>
<p>One asymmetry deserves comment. Repeating discovery inside each vendor stratum recovers the original partition much better within Siemens (ARI 0.574) than within GE (ARI 0.069). The cohort is GE-dominated (628 versus 294), so the raw Cluster 0 is essentially “the GE patients” and carries little internal structure to recover, whereas the smaller Siemens stratum retains a more distinctive feature profile. This is consistent with a partition built from vendor identity rather than biology, and it is also a reminder that within-vendor checks need to be interpreted against stratum size.</p>
</section>
<section id="limitations" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="limitations"><span class="header-section-number">5.5</span> Limitations</h2>
<p>The HR+/HER2+ survival analysis rests on 10 events. The divergence between subgroups is dramatic and the confidence interval is correspondingly wide; a larger cohort would be needed to quantify any subtype-specific prognostic effect, and this constraint is endemic to medical imaging analysis.</p>
<p>k-means on principal components was legible and adequate for a falsification exercise, but the technical-confounding argument would be strengthened by repeating it under other unsupervised algorithms.</p>
<p>Harmonization is not ground truth. ComBat and residualization remove technical effects, but the post-harmonization subgroups are not thereby biological. Harmonization should be treated as an adversary in the falsification chain, not as an assurance of validity.</p>
</section>
</section>
<section id="conclusion" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Conclusion</h1>
<p>Radiomic phenotypes can be internally stable, visually coherent and apparently prognostic while failing multiple tests of biological identity. On a 922-patient multi-vendor breast-MRI cohort, a standard unsupervised workflow produced a stable, vascularity-like two-cluster solution that appeared to carry strong prognostic information in HR+/HER2+ disease. Acquisition-aware falsification changed the interpretation on every count: the leading components and the cluster labels were dominated by manufacturer and pulse-sequence structure; manufacturer adjustment removed the survival association; and residualization or ComBat replaced the original patient partition while leaving its internal stability untouched.</p>
<p>The broad claim is methodological. Stability is the first step of radiomic phenotype validation, not the last. Internal consistency should be accompanied by multi-condition discovery, harmonization sensitivity and within-vendor sanity checks. The analysis here is breast MRI, but the principle applies to any multi-centre or multi-vendor radiomics or imaging-AI setting in which technical variance is stable enough to be mistaken for biology.</p>
</section>
<section id="sec-supplement" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Supplementary material</h1>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>S1 · Structural interpretation of the raw PCA and clustering output
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 72%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: left;">Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Scree plot</td>
<td style="text-align: left;">Variance declines progressively with no elbow; component count is a modelling choice</td>
</tr>
<tr class="even">
<td style="text-align: left;">PC1–PC2 scatter</td>
<td style="text-align: left;">Patients form a continuous distribution, so any boundary is a gradient cut</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Silhouette / CH at k = 2</td>
<td style="text-align: left;">Best on two of three metrics; Davies–Bouldin selects against k = 2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bootstrap ARI 0.893</td>
<td style="text-align: left;">The partition is reproducible under resampling</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cluster–manufacturer χ²</td>
<td style="text-align: left;">Reproducibility is inherited from the vendor split</td>
</tr>
<tr class="even">
<td style="text-align: left;">Post-harmonization ARI</td>
<td style="text-align: left;">Stability is retained; identity is not</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>S2 · Raw cluster assignment by molecular subtype and by recurrence
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-execution_count="26">
<div id="tbl-supp-xtabs" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="26">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-supp-xtabs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;12
</figcaption>
<div aria-describedby="tbl-supp-xtabs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="26">
<p><strong>By molecular subtype</strong></p>
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Cluster</th>
<th style="text-align: right;">HER2-enriched</th>
<th style="text-align: right;">HR+/HER2+</th>
<th style="text-align: right;">Luminal-like</th>
<th style="text-align: right;">Triple negative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cluster 0</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">383</td>
<td style="text-align: right;">106</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cluster 1</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">212</td>
<td style="text-align: right;">58</td>
</tr>
</tbody>
</table>
<p><strong>By recurrence event</strong></p>
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Cluster</th>
<th style="text-align: right;">No recurrence</th>
<th style="text-align: right;">Recurrence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cluster 0</td>
<td style="text-align: right;">527</td>
<td style="text-align: right;">57</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cluster 1</td>
<td style="text-align: right;">306</td>
<td style="text-align: right;">30</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Neither cross-tabulation shows the concentration that the manufacturer cross-tabulation shows. That contrast is the whole of <a href="#sec-km2" class="quarto-xref">Section&nbsp;4.2</a> in two tables.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>S3 · Biological interpretation of the dominant feature patterns
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 22%">
<col style="width: 53%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Feature category</th>
<th style="text-align: left;">Cluster pattern</th>
<th style="text-align: left;">Interpretation offered by the language</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SER entropy</td>
<td style="text-align: left;">Elevated in Cluster 1</td>
<td style="text-align: left;">Greater enhancement heterogeneity</td>
</tr>
<tr class="even">
<td style="text-align: left;">SER homogeneity</td>
<td style="text-align: left;">Elevated in Cluster 0</td>
<td style="text-align: left;">More spatially uniform enhancement</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PE variability</td>
<td style="text-align: left;">Elevated in Cluster 1</td>
<td style="text-align: left;">Less uniform peak enhancement</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wash-in / washout slopes</td>
<td style="text-align: left;">Differ between clusters</td>
<td style="text-align: left;">Perfusion-kinetic difference</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Enhancement-volume ratios</td>
<td style="text-align: left;">Differ between clusters</td>
<td style="text-align: left;">Differing enhancing tissue fraction</td>
</tr>
</tbody>
</table>
<p>Each row is a plausible sentence. None of them is evidence, because the same features are acquisition-sensitive (<a href="#fig-eta2" class="quarto-xref">Figure&nbsp;8</a>).</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>S4 · Within-vendor discovery
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-execution_count="27">
<div id="tbl-supp-vendor" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="27">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-supp-vendor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13
</figcaption>
<div aria-describedby="tbl-supp-vendor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="27">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Manufacturer</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">ARI vs raw labels</th>
<th style="text-align: right;">Silhouette</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Siemens</td>
<td style="text-align: right;">294</td>
<td style="text-align: right;">0.574</td>
<td style="text-align: right;">0.201</td>
</tr>
<tr class="even">
<td style="text-align: left;">GE</td>
<td style="text-align: right;">628</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">0.140</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>S5 · Notes on figures dropped from the source manuscript
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Two supplementary figures in the original Word manuscript duplicated main-text figures — a PCA projection coloured by manufacturer and one coloured by raw cluster, both already shown in <a href="#fig-pca" class="quarto-xref">Figure&nbsp;7</a> — and have been folded into the interactive toggle above rather than repeated. Supplementary Figure S1 (cluster distribution within each manufacturer) is the transpose of <a href="#fig-composition" class="quarto-xref">Figure&nbsp;6</a> and is likewise not repeated.</p>
</div>
</div>
</div>
</section>
<section id="sec-repro" class="level1 unnumbered">
<h1 class="unnumbered">Reproducibility</h1>
<p>Every number, table and figure on this page is generated at render time from the pipeline’s own outputs — nothing is transcribed by hand.</p>
<div class="cell" data-execution_count="28">
<div id="tbl-provenance" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="28">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-provenance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;14: What produces what.
</figcaption>
<div aria-describedby="tbl-provenance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="28">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Component</th>
<th style="text-align: left;">Location</th>
<th style="text-align: left;">Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Analysis pipeline</td>
<td style="text-align: left;"><code>src/radiomics_stability/</code></td>
<td style="text-align: left;">Preprocessing, PCA, k-means, stability, harmonization, survival</td>
</tr>
<tr class="even">
<td style="text-align: left;">Export step</td>
<td style="text-align: left;"><code>_prep/export_data.py</code></td>
<td style="text-align: left;">Slims the pipeline outputs into the CSVs this page reads</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Figure theme</td>
<td style="text-align: left;"><code>_theme.py</code></td>
<td style="text-align: left;">Palette, typography and light/dark rendering</td>
</tr>
<tr class="even">
<td style="text-align: left;">Figure builders</td>
<td style="text-align: left;"><code>_figures.py</code></td>
<td style="text-align: left;">Every figure on this page</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Data layer</td>
<td style="text-align: left;"><code>_data/*.csv</code></td>
<td style="text-align: left;">Patient-level frame, variance, η², KM curves, result tables</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Seeds and hyperparameters are fixed in the pipeline’s <code>config.py</code> (<code>RANDOM_SEED = 42</code>, 20 bootstrap iterations at 80% subsampling, <code>n_init = 20</code>). PCA variance ratios are recomputed here by SVD on the z-scored matrix and reproduce the pipeline’s values; the η² figures reproduce the source manuscript’s Table 9 under the same grouping convention, with the sensitivity analysis noted in <a href="#sec-km2" class="quarto-xref">Section&nbsp;4.2</a>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Departures from the source Word manuscript
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>These are corrections, not reinterpretations. The analysis is unchanged.</p>
<ul>
<li><strong>Table 12 and heading 5.4</strong> did not exist in the source; numbering here is continuous and generated.</li>
<li><strong>Two supplementary figures</strong> duplicated main-text figures and were dropped (S5 above).</li>
<li><strong>SER</strong> was defined inconsistently — “signal-enhancement ratio” in the results and “surface-enhancement-return” in the discussion. The first is correct and is used throughout.</li>
<li><strong>The unadjusted Cox p-value</strong> was reported as 0.02; the pipeline value is 0.025.</li>
<li><strong>Zwanenburg et al.</strong> was cited in text as 2020 but listed as the 2016 arXiv preprint; the published 2020 <em>Radiology</em> version is cited here.</li>
<li><strong>Leithner et al.&nbsp;(2022)</strong> was cited in text but listed under a co-author’s name; the reference is corrected to its first author.</li>
<li><strong>A within-vendor asymmetry</strong> (ARI 0.574 Siemens vs 0.069 GE) was present in the pipeline output but not discussed in the source; it is addressed in the discussion.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="references" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-aerts2014" class="csl-entry" role="listitem">
Aerts, Hugo J. W. L., Emmanuel Rios Velazquez, Ralph T. H. Leijenaar, et al. 2014. <span>“Decoding Tumour Phenotype by Noninvasive Imaging Using a Quantitative Radiomics Approach.”</span> <em>Nature Communications</em> 5 (1): 4006. <a href="https://doi.org/10.1038/ncomms5006">https://doi.org/10.1038/ncomms5006</a>.
</div>
<div id="ref-berenguer2018" class="csl-entry" role="listitem">
Berenguer, Roberto, María del Rosario Pastor-Juan, Jesús Canales-Vázquez, et al. 2018. <span>“Radiomics of <span>CT</span> Features May Be Nonreproducible and Redundant: Influence of <span>CT</span> Acquisition Parameters.”</span> <em>Radiology</em> 288 (2): 407–15. <a href="https://doi.org/10.1148/radiol.2018172361">https://doi.org/10.1148/radiol.2018172361</a>.
</div>
<div id="ref-collins2015" class="csl-entry" role="listitem">
Collins, Gary S., Johannes B. Reitsma, Douglas G. Altman, and Karel G. M. Moons. 2015. <span>“Transparent Reporting of a Multivariable Prediction Model for Individual Prognosis or Diagnosis (<span>TRIPOD</span>): The <span>TRIPOD</span> Statement.”</span> <em>British Journal of Surgery</em> 102 (3): 148–58. <a href="https://doi.org/10.1002/bjs.9736">https://doi.org/10.1002/bjs.9736</a>.
</div>
<div id="ref-daano2020" class="csl-entry" role="listitem">
Da-Ano, Ronrick, Dimitris Visvikis, and Mathieu Hatt. 2020. <span>“Harmonization Strategies for Multicenter Radiomics Investigations.”</span> <em>Physics in Medicine &amp; Biology</em> 65 (24): 24TR02. <a href="https://doi.org/10.1088/1361-6560/aba798">https://doi.org/10.1088/1361-6560/aba798</a>.
</div>
<div id="ref-doran2021" class="csl-entry" role="listitem">
<span class="nocase">Doran, Simon J., Santosh Kumar, Matthew Orton, et al.</span> 2021. <span>“<span>‘Real-World’</span> Radiomics from Multi-Vendor <span>MRI</span>: An Original Retrospective Study on the Prediction of Nodal Status and Disease Survival in Breast Cancer, as an Exemplar to Promote Discussion of the Wider Issues.”</span> <em>Cancer Imaging</em> 21 (1): 37. <a href="https://doi.org/10.1186/s40644-021-00406-6">https://doi.org/10.1186/s40644-021-00406-6</a>.
</div>
<div id="ref-duron2019" class="csl-entry" role="listitem">
Duron, Loic, Daniel Balvay, Saïd Vande Perre, et al. 2019. <span>“Gray-Level Discretization Impacts Reproducible <span>MRI</span> Radiomics Texture Features.”</span> <em>PLOS ONE</em> 14 (3): e0213459. <a href="https://doi.org/10.1371/journal.pone.0213459">https://doi.org/10.1371/journal.pone.0213459</a>.
</div>
<div id="ref-fortin2018" class="csl-entry" role="listitem">
Fortin, Jean-Philippe, Nicholas Cullen, Yvette I. Sheline, et al. 2018. <span>“Harmonization of Cortical Thickness Measurements Across Scanners and Sites.”</span> <em>NeuroImage</em> 167: 104–20. <a href="https://doi.org/10.1016/j.neuroimage.2017.11.024">https://doi.org/10.1016/j.neuroimage.2017.11.024</a>.
</div>
<div id="ref-gillies2016" class="csl-entry" role="listitem">
Gillies, Robert J., Paul E. Kinahan, and Hedvig Hricak. 2016. <span>“Radiomics: Images Are More Than Pictures, They Are Data.”</span> <em>Radiology</em> 278 (2): 563–77. <a href="https://doi.org/10.1148/radiol.2015151169">https://doi.org/10.1148/radiol.2015151169</a>.
</div>
<div id="ref-handl2005" class="csl-entry" role="listitem">
Handl, Julia, Joshua Knowles, and Douglas B. Kell. 2005. <span>“Computational Cluster Validation in Post-Genomic Data Analysis.”</span> <em>Bioinformatics</em> 21 (15): 3201–12. <a href="https://doi.org/10.1093/bioinformatics/bti517">https://doi.org/10.1093/bioinformatics/bti517</a>.
</div>
<div id="ref-johnson2007" class="csl-entry" role="listitem">
Johnson, W. Evan, Cheng Li, and Ariel Rabinovic. 2007. <span>“Adjusting Batch Effects in Microarray Expression Data Using Empirical <span>B</span>ayes Methods.”</span> <em>Biostatistics</em> 8 (1): 118–27. <a href="https://doi.org/10.1093/biostatistics/kxj037">https://doi.org/10.1093/biostatistics/kxj037</a>.
</div>
<div id="ref-lambin2012" class="csl-entry" role="listitem">
Lambin, Philippe, Emmanuel Rios-Velazquez, Ralph Leijenaar, et al. 2012. <span>“Radiomics: Extracting More Information from Medical Images Using Advanced Feature Analysis.”</span> <em>European Journal of Cancer</em> 48 (4): 441–46. <a href="https://doi.org/10.1016/j.ejca.2011.11.036">https://doi.org/10.1016/j.ejca.2011.11.036</a>.
</div>
<div id="ref-leijenaar2015" class="csl-entry" role="listitem">
Leijenaar, Ralph T. H., Georgi Nalbantov, Sara Carvalho, et al. 2015. <span>“The Effect of <span>SUV</span> Discretization in Quantitative <span>FDG-PET</span> Radiomics: The Need for Standardized Methodology in Tumor Texture Analysis.”</span> <em>Scientific Reports</em> 5 (1): 11075. <a href="https://doi.org/10.1038/srep11075">https://doi.org/10.1038/srep11075</a>.
</div>
<div id="ref-leithner2022" class="csl-entry" role="listitem">
Leithner, Doris, Heiko Schöder, Alexander Haug, et al. 2022. <span>“Impact of <span>ComBat</span> Harmonization on <span>PET</span> Radiomics-Based Tissue Classification: A Dual-Center <span>PET/MRI</span> and <span>PET/CT</span> Study.”</span> <em>Journal of Nuclear Medicine</em> 63 (10): 1611–16. <a href="https://doi.org/10.2967/jnumed.121.263102">https://doi.org/10.2967/jnumed.121.263102</a>.
</div>
<div id="ref-li2018" class="csl-entry" role="listitem">
Li, Hongming, Maya Galperin-Aizenberg, Daniel Pryma, Charles B. Simone II, and Yong Fan. 2018. <span>“Unsupervised Machine Learning of Radiomic Features for Predicting Treatment Response and Overall Survival of Early Stage Non-Small Cell Lung Cancer Patients Treated with Stereotactic Body Radiation Therapy.”</span> <em>Radiotherapy and Oncology</em> 129 (2): 218–26. <a href="https://doi.org/10.1016/j.radonc.2018.06.025">https://doi.org/10.1016/j.radonc.2018.06.025</a>.
</div>
<div id="ref-lozano2024" class="csl-entry" role="listitem">
Lozano-Montoya, Jorge, and Ana Jimenez-Pastor. 2024. <span>“Harmonization in the Features Domain.”</span> In <em>Basics of Image Processing: The Facts and Challenges of Data Harmonization to Improve Radiomics Reproducibility</em>. Springer International Publishing. <a href="https://doi.org/10.1007/978-3-031-48446-9_7">https://doi.org/10.1007/978-3-031-48446-9_7</a>.
</div>
<div id="ref-lu2021" class="csl-entry" role="listitem">
Lu, Lin, Firas S. Ahmed, Oguz Akin, et al. 2021. <span>“Uncontrolled Confounders May Lead to False or Overvalued Radiomics Signature: A Proof of Concept Using Survival Analysis in a Multicenter Cohort of Kidney Cancer.”</span> <em>Frontiers in Oncology</em> 11: 638185. <a href="https://doi.org/10.3389/fonc.2021.638185">https://doi.org/10.3389/fonc.2021.638185</a>.
</div>
<div id="ref-mackin2015" class="csl-entry" role="listitem">
Mackin, Dennis, Xenia Fave, Lifei Zhang, et al. 2015. <span>“Measuring Computed Tomography Scanner Variability of Radiomics Features.”</span> <em>Investigative Radiology</em> 50 (11): 757–65. <a href="https://doi.org/10.1097/RLI.0000000000000180">https://doi.org/10.1097/RLI.0000000000000180</a>.
</div>
<div id="ref-nyul1999" class="csl-entry" role="listitem">
Nyúl, László G., and Jayaram K. Udupa. 1999. <span>“On Standardizing the <span>MR</span> Image Intensity Scale.”</span> <em>Magnetic Resonance in Medicine</em> 42 (6): 1072–81. <a href="https://doi.org/10.1002/(SICI)1522-2594(199912)42:6<1072::AID-MRM11>3.0.CO;2-M">https://doi.org/10.1002/(SICI)1522-2594(199912)42:6&lt;1072::AID-MRM11&gt;3.0.CO;2-M</a>.
</div>
<div id="ref-park2020" class="csl-entry" role="listitem">
Park, Ji Eun, Donghyun Kim, Ho Sung Kim, et al. 2020. <span>“Quality of Science and Reporting of Radiomics in Oncologic Studies: Room for Improvement According to Radiomics Quality Score and <span>TRIPOD</span> Statement.”</span> <em>European Radiology</em> 30 (1): 523–36. <a href="https://doi.org/10.1007/s00330-019-06360-z">https://doi.org/10.1007/s00330-019-06360-z</a>.
</div>
<div id="ref-parmar2015" class="csl-entry" role="listitem">
Parmar, Chintan, Patrick Grossmann, Derek Rietveld, Michelle M. Rietbergen, Philippe Lambin, and Hugo J. W. L. Aerts. 2015. <span>“Radiomic Machine-Learning Classifiers for Prognostic Biomarkers of Head and Neck Cancer.”</span> <em>Frontiers in Oncology</em> 5: 272. <a href="https://doi.org/10.3389/fonc.2015.00272">https://doi.org/10.3389/fonc.2015.00272</a>.
</div>
<div id="ref-pinker2018" class="csl-entry" role="listitem">
Pinker, Katja, Joanne Chin, Amy N. Melsaether, Elizabeth A. Morris, and Linda Moy. 2018. <span>“Precision Medicine and Radiogenomics in Breast Cancer: New Approaches Toward Diagnosis and Treatment.”</span> <em>Radiology</em> 287 (3): 732–47. <a href="https://doi.org/10.1148/radiol.2018172171">https://doi.org/10.1148/radiol.2018172171</a>.
</div>
<div id="ref-saha2018" class="csl-entry" role="listitem">
Saha, Ashirbani, Michael R. Harowicz, Lars J. Grimm, et al. 2018. <span>“A Machine Learning Approach to Radiogenomics of Breast Cancer: A Study of 922 Subjects and 529 <span>DCE-MRI</span> Features.”</span> <em>British Journal of Cancer</em> 119 (4): 508–16. <a href="https://doi.org/10.1038/s41416-018-0185-8">https://doi.org/10.1038/s41416-018-0185-8</a>.
</div>
<div id="ref-saha2021data" class="csl-entry" role="listitem">
Saha, Ashirbani, Michael R. Harowicz, Lars J. Grimm, et al. 2021. <em>Dynamic Contrast-Enhanced Magnetic Resonance Images of Breast Cancer Patients with Tumor Locations</em>. The Cancer Imaging Archive. <a href="https://doi.org/10.7937/TCIA.e3sv-re93">https://doi.org/10.7937/TCIA.e3sv-re93</a>.
</div>
<div id="ref-traverso2018" class="csl-entry" role="listitem">
Traverso, Alberto, Leonard Wee, Andre Dekker, and Robert Gillies. 2018. <span>“Repeatability and Reproducibility of Radiomic Features: A Systematic Review.”</span> <em>International Journal of Radiation Oncology, Biology, Physics</em> 102 (4): 1143–58. <a href="https://doi.org/10.1016/j.ijrobp.2018.05.053">https://doi.org/10.1016/j.ijrobp.2018.05.053</a>.
</div>
<div id="ref-yamamoto2012" class="csl-entry" role="listitem">
Yamamoto, Shota, Daniel D. Maki, Ronald L. Korn, and Michael D. Kuo. 2012. <span>“Radiogenomic Analysis of Breast Cancer Using <span>MRI</span>: A Preliminary Study to Define the Landscape.”</span> <em>American Journal of Roentgenology</em> 199 (3): 654–63. <a href="https://doi.org/10.2214/AJR.11.7824">https://doi.org/10.2214/AJR.11.7824</a>.
</div>
<div id="ref-zwanenburg2020" class="csl-entry" role="listitem">
<span class="nocase">Zwanenburg, Alex, Martin Vallières, Mahmoud A. Abdalah, et al.</span> 2020. <span>“The Image Biomarker Standardization Initiative: Standardized Quantitative Radiomics for High-Throughput Image-Based Phenotyping.”</span> <em>Radiology</em> 295 (2): 328–38. <a href="https://doi.org/10.1148/radiol.2020191145">https://doi.org/10.1148/radiol.2020191145</a>.
</div>
</div>


</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/MalekItani\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Malek M. Itani</p>
</div>   
    <div class="nav-footer-center">
<p>Built with <a href="https://quarto.org">Quarto</a></p>
</div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Ma-Mar-Itan">
      <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/malek-ma-itani/">
      <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="mailto:Malek.Ma.Itani@gmail.com">
      <i class="bi bi-envelope" role="img" aria-label="Email">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>