<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Malek M. Itani">
<meta name="dcterms.date" content="2026-06-16">
<meta name="description" content="Detecting sensor induced effects on high dimensional data.">

<title>Acquisition-Aware Falsification of Unsupervised Radiomic Phenotypes in Multi-Vendor Breast MRI – Malek M. Itani</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../assets/img/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-73b0ff3878a4e6fc3716dc69a6aaefa3.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-a60fab2f8a066d0ce7bf48d8b28043cc.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-73b0ff3878a4e6fc3716dc69a6aaefa3.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-8b301e166ad655f7235e209fb6f9e183.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-3604137813e22fcfa8362079520af3ac.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-8b301e166ad655f7235e209fb6f9e183.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Newsreader:ital,opsz,wght@0,6..72,400;0,500;0,600;1,6..72,400&amp;family=Inter:wght@400;500;600&amp;family=JetBrains+Mono:wght@400;500&amp;display=swap" rel="stylesheet">


<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Acquisition-Aware Falsification of Unsupervised Radiomic Phenotypes in Multi-Vendor Breast MRI – Malek M. Itani">
<meta property="og:description" content="Detecting sensor induced effects on high dimensional data.">
<meta property="og:image" content="https://ma-mar-itan.github.io/PortfolioWebsite/research/Acquisition-Aware Falsification/figures/fig-thumb-light.svg">
<meta property="og:site_name" content="Malek M. Itani">
<meta property="og:image:alt" content="Two scatterplots of the same points, coloured by cluster and by scanner — indistinguishable">
<meta name="twitter:title" content="Acquisition-Aware Falsification of Unsupervised Radiomic Phenotypes in Multi-Vendor Breast MRI – Malek M. Itani">
<meta name="twitter:description" content="Detecting sensor induced effects on high dimensional data.">
<meta name="twitter:image" content="https://ma-mar-itan.github.io/PortfolioWebsite/research/Acquisition-Aware Falsification/figures/fig-thumb-light.svg">
<meta name="twitter:image:alt" content="Two scatterplots of the same points, coloured by cluster and by scanner — indistinguishable">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../assets/img/logo.svg" alt="Site logo" class="navbar-logo light-content">
    <img src="../../assets/img/logo.svg" alt="Site logo" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Malek M. Itani</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../blog/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../research/index.html"> 
<span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../prototypes/index.html"> 
<span class="menu-text">Prototypes</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About me</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Ma-Mar-Itan" target="_blank"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/malek-ma-itani/" target="_blank"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../blog/index.xml"> <i class="bi bi-rss" role="img" aria-label="RSS feed">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#background-and-rationale" id="toc-background-and-rationale" class="nav-link" data-scroll-target="#background-and-rationale">2. Background and Rationale</a>
  <ul class="collapse">
  <li><a href="#radiomic-phenotype-discovery" id="toc-radiomic-phenotype-discovery" class="nav-link" data-scroll-target="#radiomic-phenotype-discovery">Radiomic phenotype discovery</a></li>
  <li><a href="#supervised-versus-unsupervised-settings" id="toc-supervised-versus-unsupervised-settings" class="nav-link" data-scroll-target="#supervised-versus-unsupervised-settings">Supervised versus unsupervised settings</a></li>
  <li><a href="#technical-variance-in-radiomics" id="toc-technical-variance-in-radiomics" class="nav-link" data-scroll-target="#technical-variance-in-radiomics">Technical variance in radiomics</a></li>
  <li><a href="#harmonization-and-its-limits" id="toc-harmonization-and-its-limits" class="nav-link" data-scroll-target="#harmonization-and-its-limits">Harmonization and its limits</a></li>
  <li><a href="#the-validation-gap" id="toc-the-validation-gap" class="nav-link" data-scroll-target="#the-validation-gap">The validation gap</a></li>
  </ul></li>
  <li><a href="#materials-and-methods" id="toc-materials-and-methods" class="nav-link" data-scroll-target="#materials-and-methods">3. Materials and Methods</a>
  <ul class="collapse">
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">3.1 Data</a></li>
  <li><a href="#standard-phenotype-discovery" id="toc-standard-phenotype-discovery" class="nav-link" data-scroll-target="#standard-phenotype-discovery">3.2 Standard phenotype discovery</a></li>
  <li><a href="#falsification-chain-and-technical-adjudication" id="toc-falsification-chain-and-technical-adjudication" class="nav-link" data-scroll-target="#falsification-chain-and-technical-adjudication">3.3 Falsification chain and technical adjudication</a></li>
  <li><a href="#clinical-and-biomarker-evaluation" id="toc-clinical-and-biomarker-evaluation" class="nav-link" data-scroll-target="#clinical-and-biomarker-evaluation">3.4 Clinical and biomarker evaluation</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">4. Results</a>
  <ul class="collapse">
  <li><a href="#key-message-1-a-standard-workflow-creates-a-plausible-but-fragile-discovery" id="toc-key-message-1-a-standard-workflow-creates-a-plausible-but-fragile-discovery" class="nav-link" data-scroll-target="#key-message-1-a-standard-workflow-creates-a-plausible-but-fragile-discovery">4.1 Key message 1: a standard workflow creates a plausible but fragile discovery</a></li>
  <li><a href="#key-message-2-the-apparent-phenotype-is-acquisition-dominated-not-subtype-defined" id="toc-key-message-2-the-apparent-phenotype-is-acquisition-dominated-not-subtype-defined" class="nav-link" data-scroll-target="#key-message-2-the-apparent-phenotype-is-acquisition-dominated-not-subtype-defined">4.2 Key message 2: the apparent phenotype is acquisition-dominated, not subtype-defined</a></li>
  <li><a href="#key-message-3-harmonization-preserves-bootstrap-stability-but-destroys-partition-identity" id="toc-key-message-3-harmonization-preserves-bootstrap-stability-but-destroys-partition-identity" class="nav-link" data-scroll-target="#key-message-3-harmonization-preserves-bootstrap-stability-but-destroys-partition-identity">4.3 Key message 3: harmonization preserves bootstrap stability but destroys partition identity</a></li>
  <li><a href="#key-message-4-neither-the-hrher2-signal-nor-the-residual-size-linked-structure-supports-a-biomarker-claim" id="toc-key-message-4-neither-the-hrher2-signal-nor-the-residual-size-linked-structure-supports-a-biomarker-claim" class="nav-link" data-scroll-target="#key-message-4-neither-the-hrher2-signal-nor-the-residual-size-linked-structure-supports-a-biomarker-claim">4.4 Key message 4: neither the HR+/HER2+ signal nor the residual size-linked structure supports a biomarker claim</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">5. Discussion</a>
  <ul class="collapse">
  <li><a href="#main-finding-the-negative-result-is-the-result" id="toc-main-finding-the-negative-result-is-the-result" class="nav-link" data-scroll-target="#main-finding-the-negative-result-is-the-result">5.1 Main finding: the negative result is the result</a></li>
  <li><a href="#dangers-of-language" id="toc-dangers-of-language" class="nav-link" data-scroll-target="#dangers-of-language">5.2 Dangers of Language</a></li>
  <li><a href="#cluster-stability-and-partition-identity-are-separate-validation-targets" id="toc-cluster-stability-and-partition-identity-are-separate-validation-targets" class="nav-link" data-scroll-target="#cluster-stability-and-partition-identity-are-separate-validation-targets">5.3 Cluster stability and partition identity are separate validation targets</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">5.5 Limitations</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">6. Conclusion</a></li>
  <li><a href="#supplementary-material" id="toc-supplementary-material" class="nav-link" data-scroll-target="#supplementary-material">Supplementary Material</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Acquisition-Aware Falsification of Unsupervised Radiomic Phenotypes in Multi-Vendor Breast MRI</h1>
<p class="subtitle lead">A falsification framework for acquisition-driven radiomic phenotypes</p>
  <div class="quarto-categories">
    <div class="quarto-category">Radiomics</div>
    <div class="quarto-category">Medical imaging</div>
    <div class="quarto-category">Clustering</div>
    <div class="quarto-category">Reproducibility</div>
  </div>
  </div>

<div>
  <div class="description">
    <p>Detecting sensor induced effects on high dimensional data.</p>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Malek M. Itani </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 16, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="title-page">
<p>BEIRUT ARAB UNIVERSITY<br>
Faculty of Science<br>
Department of Mathematics<br>
Project · Medical Statistics<br>
Trapped by Stability:<br>
A Falsification Framework for Acquisition-Driven Radiomic Phenotypes<br>
PREPARED BY Malek M. Itani<br>
SUPERVISED BY Dr.&nbsp;Lama Affara<br>
ACADEMIC YEAR 2025 – 2026</p>
</div>
<section id="abstract" class="level1">
<h1>Abstract</h1>
<p>In this work, we do not offer an additional radiomic phenotype from breast MRI, but rather we expose a type of failure mode of phenotype claims that may succeed at standard internal validation: the stability trap. Specifically, one can generate a partition that is reproducible to resampling, shows what could otherwise be mistaken for prognostic signal but have no underlying biology in common. We generated via a common unsupervised pipeline the kind of result that could easily be overinterpreted from a large 922 patient multi-vendor breast MRI dataset. This included creating a reproducible two-cluster partition with enhancement- like, vascularity feature differences as well as a recurrence-free survival relationships in HR+/HER2+ disease. We submit this negative result as a case of falsification, not as a biomarker option. Scanner identity and pulse-sequence basis were each strongly associated with the unsupervised partition. In contrast, subtype and whole-cohort recurrence were weakly associated with clusters. Harmonization through manufacturer residualization or ComBat eliminated the HR+/HER2+ survival relationship and maintained internal clusterability at the expense of the initial patient partitioning. While the harmonization informed or residualized postprocessing association structure was statistically cleaner, it did not pass biological plausibility checks and was more strongly correlated with tumour size than recurrence or subtype. Our primary contribution is therefore a framework: we offer a falsification benchmark to test radiomic phenotype claims. Discovery across multiple conditions, sensitivity to harmonization, and within vendor sanity checks are among the minimum recommended checks we propose for multi-vendor MRI, multicenter radiomics work and AI image studies where technical noise can overfit as if it were biology.</p>
<p>Keywords</p>
<p>Breast MRI; radiomics; phenotype discovery; ComBat harmonization; acquisition confounding; cluster stability; cluster identity; imaging AI reproducibility.</p>
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>One of the promises of the field of radiomics, is the ability to identify latent imaging subgroups representing phenotypes undetectable to standard labelling methods. Imaging methods such as breast MRI and dynamic contrast-enhanced imaging allows for the generation of quantitative features describing hidden heterogeneity in tumour morphology, vascularity and cellularity that can be utilized in unsupervised machine learning techniques. In theory this practice would allow physicians to capture stable cluster associated structures with meaningful biological variations that go beyond standard procedures of relying on receptor base labelling <span class="citation" data-cites="lambin2012">(<a href="#ref-lambin2012" role="doc-biblioref">Lambin et al. 2012</a>)</span>.</p>
<p>In practice, multivendor sourced data sets have showcased that acquisition associated variables can influence inference through features such as manufacturer, pulse-sequence parameters, field strength, voxel geometry, reconstruction choices, and acquisition timing <span class="citation" data-cites="zwanenburg2020">(<a href="#ref-zwanenburg2020" role="doc-biblioref"><span class="nocase">Zwanenburg et al.</span> 2020</a>)</span>. When dealing with high dimensionality, even minute acquisition effects can dominate the feature space after dimensionality reduction, resulting in clustering algorithms that recover partitioning based on technology rather than biology.</p>
<p>Validation techniques rely heavily on metrics that assess reproducibility of the results rather than validity, failing to distinguish between a biologically meaningful phenotype and a technically induced one <span class="citation" data-cites="handl2005">(<a href="#ref-handl2005" role="doc-biblioref">Handl et al. 2005</a>)</span>. This overreliance on stability creates what we term “The Stability Trap”: the mathematical illusion that a data partition is biologically valid simply because its underlying technical artifact is highly stable and reproducible.</p>
<p>This distinction between stability and validity is what motivates the present study, rather than treating cluster discovery and stability as the endpoint of phenotype identification, this study proposes a falsification chain that presents any potential phenotype discovery a set of acquisition aware challenges designed to expose technical confounding.</p>
<p>The first step is evaluating the raw radiomic feature space, testing whether dominant principal components are associated with biological and/or technical acquisition variables. The second step is stress testing cluster identity; any real biological phenotype would withstand technical corrections through manufacturer residualization and ComBat harmonization. Hence phenotype discovery is repeated after taking into account manufacture effects. Similar to the second step, the final step is revaluating clinical interpretation after adjustment for manufacturer and across harmonization strategies.</p>
<p>Using our proposed falsification framework, we examine a cohort of 922 breast MRI patients. We first provide evidence of a stable two-cluster radiomic phenotype with enhancement-dominant, vascularity-like characteristics and an apparent HR+/HER2+ recurrence-free survival signal. Then we showcase that the dominant variance axes are led by acquisition parameters rather than biological factors. The contribution of this study is therefore methodological rather than biomarker-driven: it shows that a phenotype can be internally stable, visually interpretable, and apparently prognostic while still failing tests of biological identity.</p>
</section>
<section id="background-and-rationale" class="level1">
<h1>2. Background and Rationale</h1>
<section id="radiomic-phenotype-discovery" class="level2">
<h2 class="anchored" data-anchor-id="radiomic-phenotype-discovery">Radiomic phenotype discovery</h2>
<p>Radiomics allows for the extraction of quantitative information from routine medical images, and thus promises to expand the knowledge on tumour phenotype that is not captured by visual interpretation. This allows radiomics to be positioned as the main bridge between medical imaging and personalized medicine, allowing it to complement histology, genomics, and clinical covariates in risk stratification and treatment selection <span class="citation" data-cites="lambin2012">(<a href="#ref-lambin2012" role="doc-biblioref">Lambin et al. 2012</a>)</span>. One particularly relevant image modality is Breast MRI as dynamic contrast-enhanced MRI, diffusion-weighted imaging, T2-weighted imaging, and enhancement kinetics enables the acquisition of information related to vascularity, cellularity, morphology, and tissue heterogeneity <span class="citation" data-cites="pinker2018">(<a href="#ref-pinker2018" role="doc-biblioref">Pinker et al. 2018</a>)</span>.</p>
<p>While the majority of previous work has focused on supervised learning, radiomics shows great potential in the unsupervised learning subfield, where patients are clustered solely based on feature space. These clusters are then studied for associations with prognosis, molecular subtype, immune state, stromal composition, or pathway activity <span class="citation" data-cites="li2018">(<a href="#ref-li2018" role="doc-biblioref">Li et al. 2018</a>)</span>. This allows for the discovery of image derived subtypes of cancer through survival analysis, molecular pathways, and treatment response <span class="citation" data-cites="yamamoto2012 aerts2014">(<a href="#ref-yamamoto2012" role="doc-biblioref">Yamamoto et al. 2012</a>; <a href="#ref-aerts2014" role="doc-biblioref">Aerts et al. 2014</a>)</span>. Collectively, there is consensus on the great potential of radiomics to provide clinically meaningful insight on the biological variations of tumours <span class="citation" data-cites="gillies2016">(<a href="#ref-gillies2016" role="doc-biblioref">Gillies et al. 2016</a>)</span>.</p>
</section>
<section id="supervised-versus-unsupervised-settings" class="level2">
<h2 class="anchored" data-anchor-id="supervised-versus-unsupervised-settings">Supervised versus unsupervised settings</h2>
<p>What separates radiomic studies using supervised and unsupervised clustering techniques is the failure mode that supervised learning has managed to avoid albeit partially. In supervised techniques, outcomes labels are provided and exist outside of feature space, which allows the judgment of model performance to be against a predefined endpoint (molecular subtype, recurrence, or treatment response), limiting the effects of technical confounding on model inference <span class="citation" data-cites="parmar2015">(<a href="#ref-parmar2015" role="doc-biblioref">Parmar et al. 2015</a>)</span>. This has allowed supervised radiomics to advance much more rapidly towards clinical use, whereas unsupervised radiomics remains lagging <span class="citation" data-cites="park2020">(<a href="#ref-park2020" role="doc-biblioref">Park et al. 2020</a>)</span>. This external validation does not exist in unsupervised techniques, where clustering models are created based solely on the feature space that may contain scanner, protocol, or manufacturer effects. If technological differences in radiomic feature space is better positioned to explain the variance in structure, the clustering algorithms will recover these hardware-defined partitions before they encounter tumour-defined ones. And standard validation metrics such as silhouette score and bootstrap stability end up testing the reproducibility of these partitions rather their biological validity <span class="citation" data-cites="handl2005">(<a href="#ref-handl2005" role="doc-biblioref">Handl et al. 2005</a>)</span>, resulting in the “stability trap”:</p>
<p>Mathematical reproducibility can be mistaken for biological validity.</p>
</section>
<section id="technical-variance-in-radiomics" class="level2">
<h2 class="anchored" data-anchor-id="technical-variance-in-radiomics">Technical variance in radiomics</h2>
<p>The literature describing the impact of acquisition effects on radiomic features is extensive, where many features such as voxel size and gray-level discretization become nonreproducible due to acquisition variation <span class="citation" data-cites="berenguer2018 mackin2015 duron2019 leijenaar2015">(<a href="#ref-berenguer2018" role="doc-biblioref">Berenguer et al. 2018</a>; <a href="#ref-mackin2015" role="doc-biblioref">Mackin et al. 2015</a>; <a href="#ref-duron2019" role="doc-biblioref">Duron et al. 2019</a>; <a href="#ref-leijenaar2015" role="doc-biblioref">Leijenaar et al. 2015</a>)</span>. This lack of reproducibility has resulted in inability of radiomics to completely transition from theoretical work to the mainstream clinical workflow, although the great effort at standardizing the field such as the Image Biomarker Standardisation Initiative <span class="citation" data-cites="zwanenburg2020 traverso2018">(<a href="#ref-zwanenburg2020" role="doc-biblioref"><span class="nocase">Zwanenburg et al.</span> 2020</a>; <a href="#ref-traverso2018" role="doc-biblioref">Traverso et al. 2018</a>)</span>.</p>
<p>Adding greater challenge is the unstandardized nature of MRI imaging <span class="citation" data-cites="nyul1999">(<a href="#ref-nyul1999" role="doc-biblioref">Nyúl and Udupa 1999</a>)</span>, where protocols, coils and pulse sequences tend to differ across different vendors.</p>
<p>Perhaps the most direct proof-of-concept comes from multi-vendor breast MRI radiomics studies, which have shown that non-biological features can accurately predict the scanner platform and field strength with area-under-the-curve values ranging from 0.91 to 1.00 <span class="citation" data-cites="doran2021">(<a href="#ref-doran2021" role="doc-biblioref"><span class="nocase">Doran et al.</span> 2021</a>)</span>. That same study found the pipeline’s ability to predict tumour biology was only modest (AUC = 0.673 for pathological nodal status) when using radiomic features without any clinical variables. That key result illustrates that radiomic features can encode strong technical signals, and that technical structure can directly compete with tumour biology in the same feature space.</p>
</section>
<section id="harmonization-and-its-limits" class="level2">
<h2 class="anchored" data-anchor-id="harmonization-and-its-limits">Harmonization and its limits</h2>
<p>Feature-level harmonization is the current solution to unwanted scanner or site effects. Developed initially for batch-effects in gene-expression data, ComBat was later extended to neuroimaging and radiomics with the goal of removing scanner, site, and protocol effects while retaining biological information <span class="citation" data-cites="johnson2007 fortin2018">(<a href="#ref-johnson2007" role="doc-biblioref">Johnson et al. 2007</a>; <a href="#ref-fortin2018" role="doc-biblioref">Fortin et al. 2018</a>)</span>. In radiomics, ComBat and variants have been used almost exclusively to improve cross-site comparability of radiomic features or the transportability of supervised models built on those features <span class="citation" data-cites="leithner2022">(<a href="#ref-leithner2022" role="doc-biblioref">Leithner et al. 2022</a>)</span>. Harmonization has been shown to reduce batch effects and improve performance in PET radiomics studies, MRI radiomics studies, and multi-centre datasets <span class="citation" data-cites="daano2020">(<a href="#ref-daano2020" role="doc-biblioref">Da-Ano et al. 2020</a>)</span>.</p>
<p>However, existing evaluations of ComBat harmonization assume that the biomedical endpoint matters. That is fine for supervised prediction, but it does not match the logic of unsupervised phenotypes. For phenotype discovery, the key question is what happens to the patient partition after harmonization. If the cluster reflects manufacturer-related variance more than tumour biology, then ComBat may leave the mathematical stability intact while substituting a different partition that also passes validation checks. Standard validation metrics would not alert the investigator because the mathematical properties of the cluster haven’t changed, even though the biological meaning of the phenotype might have <span class="citation" data-cites="lozano2024">(<a href="#ref-lozano2024" role="doc-biblioref">Lozano-Montoya and Jimenez-Pastor 2024</a>)</span>.</p>
</section>
<section id="the-validation-gap" class="level2">
<h2 class="anchored" data-anchor-id="the-validation-gap">The validation gap</h2>
<p>It is widely accepted that for prediction modelling, performance and internal validity is not enough but rather claims should be required to go through robustness checks, stress tests and external validation for generalizability to be accepted <span class="citation" data-cites="collins2015">(<a href="#ref-collins2015" role="doc-biblioref">Collins et al. 2015</a>)</span>. In this context, any claim of phenotype discovery should be exposed to tests that aim to disprove biological interpretations. As such this study aims to define an acquisition-aware falsification chain for unsupervised radiomic phenotypes where the main question is not whether a reproducible cluster exists, but whether the same biological claim can survive when technical sources of variance are explicitly tested. This will require practitioners to ask whether clusters map more strongly to manufacturer than molecular subtypes? Whether the main principal components are dominated by acquisition variables? Whether cluster identity or prognostic relevance survive residualization and ComBat? Whether the stress tested clusters still meet minimum biomarker criteria <span class="citation" data-cites="lu2021">(<a href="#ref-lu2021" role="doc-biblioref">Lu et al. 2021</a>)</span>.</p>
<p>The contribution of the present paper is therefore methodological rather than biomarker-driven. It does not argue that unsupervised radiomic discovery is invalid in general. Instead, it argues that cluster stability is not equivalent to biological validity, especially in multi-vendor datasets. A phenotype may be internally stable, visually interpretable, and apparently prognostic while still being dominated by technical variance. While the literature has already established that feature space can be dominated by acquisition techniques, and that this can be mitigated through harmonization literature <span class="citation" data-cites="yamamoto2012 traverso2018 daano2020">(<a href="#ref-yamamoto2012" role="doc-biblioref">Yamamoto et al. 2012</a>; <a href="#ref-traverso2018" role="doc-biblioref">Traverso et al. 2018</a>; <a href="#ref-daano2020" role="doc-biblioref">Da-Ano et al. 2020</a>)</span>, what is still missing is a standardized end to end falsification pipeline to test whether a stable unsupervised cluster retains its identity and biological interpretation after known acquisition effects are adjusted for.</p>
</section>
</section>
<section id="materials-and-methods" class="level1">
<h1>3. Materials and Methods</h1>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">3.1 Data</h2>
<p>For the purpose of our analysis, we make use of a 922-patient breast MRI dataset with 529 quantitative MRI-derived radiomic features <span class="citation" data-cites="saha2021data">(<a href="#ref-saha2021data" role="doc-biblioref">Saha et al. 2021</a>)</span>. We retained variables with &lt;5% missingness and ≥ 2 unique values. Under these criteria, no features were removed. Missing values were imputed using the median and all features were standardized to have zero mean before PCA, clustering, harmonization, and survival modeling. The standardized 922 x 529 matrix is summarized in <a href="#t-1">Table 1</a>. Z-score scaling was necessary because our feature-set integrated data on enhancement kinetics, peak enhancement, signal-enhancement ratio, texture statistics, and various other feature-descriptors that were reported on different natural scales. Without standardization, methods like PCA and k-means that rely on variance would be biased by numerical scale rather than data structure.</p>
<div id="t-1" class="table-caption">
<p>Table 1. Radiomic matrix and preprocessing summary.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Step</th>
<th>Patients</th>
<th>Features</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Raw imaging matrix</td>
<td>922</td>
<td>529</td>
<td>Numeric MRI-derived radiomic feature matrix after patient ID removal.</td>
</tr>
<tr class="even">
<td>Missingness filtering</td>
<td>922</td>
<td>529</td>
<td>No variables exceeded the &lt;5% missingness threshold.</td>
</tr>
<tr class="odd">
<td>Low-variance filtering</td>
<td>922</td>
<td>529</td>
<td>No variables failed the &gt;=2 unique-value criterion.</td>
</tr>
<tr class="even">
<td>Median imputation</td>
<td>922</td>
<td>529</td>
<td>Residual missing values imputed feature-wise.</td>
</tr>
<tr class="odd">
<td>Z-score standardization</td>
<td>922</td>
<td>529</td>
<td>Mean-centered and variance-scaled matrix generated.</td>
</tr>
<tr class="even">
<td>Final analysis matrix</td>
<td>922</td>
<td>529</td>
<td>Input for PCA, clustering, harmonization, and survival modeling.</td>
</tr>
</tbody>
</table>
</section>
<section id="standard-phenotype-discovery" class="level2">
<h2 class="anchored" data-anchor-id="standard-phenotype-discovery">3.2 Standard phenotype discovery</h2>
<p>Principal component analysis (PCA) was applied to the standardized radiomic data. The PCs that explained the most variance were selected for exploratory visualization and clustering. Clustering was performed via K-means for a group of candidate k values. Internal validity metrics were summarized with silhouette score, Calinski-Harabasz index, and Davies-Bouldin index. Bootstrap stability was assessed by repeated 80% subsampling and reported with the adjusted Rand index (ARI). Feature differences between clusters were assessed via Welch tests. This process was performed on the raw partition to determine whether the PCs possessed a coherent imaging interpretation before any technical challenge was applied.</p>
</section>
<section id="falsification-chain-and-technical-adjudication" class="level2">
<h2 class="anchored" data-anchor-id="falsification-chain-and-technical-adjudication">3.3 Falsification chain and technical adjudication</h2>
<p>The falsification chain consisted of four steps. Technical enrichment was first measured by comparing cluster labels and PC structure with acquisition variables, then Phenotype discovery was secondly repeated after manufacturer residualization and ComBat harmonization. Partition identity was thirdly quantified by comparing harmonized labels with raw labels using ARI. Finally, clinical interpretability was retested after manufacturer adjustment.</p>
</section>
<section id="clinical-and-biomarker-evaluation" class="level2">
<h2 class="anchored" data-anchor-id="clinical-and-biomarker-evaluation">3.4 Clinical and biomarker evaluation</h2>
<p>The top screen was assessed for recurrence-free survival in the HR+/HER2+ subgroup first, as this is where the raw phenotype exhibited its most significant survival split. Kaplan-Meier curves, log-rank tests and Cox proportional-hazards modeling were utilized. The cluster effect was then subjected to manufacturer-adjusted Cox modeling to determine whether an effect could still be interpreted after technical adjustment. Association of this post-harmonization structure with prespecified biomarker criteria was then evaluated. These criteria are deliberately minimal standards for identification and are not confirmation of biological validity.</p>
</section>
</section>
<section id="results" class="level1">
<h1>4. Results</h1>
<section id="key-message-1-a-standard-workflow-creates-a-plausible-but-fragile-discovery" class="level2">
<h2 class="anchored" data-anchor-id="key-message-1-a-standard-workflow-creates-a-plausible-but-fragile-discovery">4.1 Key message 1: a standard workflow creates a plausible but fragile discovery</h2>
<p>At first glance, the results give off a valid impression of a phenotypic discovery. First, principal component analysis shows a structured feature space where the top 10 principal components are able to explain 58% of the variance (See <a href="#t-2">Table 2</a>), with principal component one, two and three explaining 15.5%, 9.6% and 7.8% respectively. Scree plots and PC1-PC2 projections are reported below in <a href="#f-1">Figures 1</a> and <a href="#f-2">2</a>, where it is showcased that patient distribution took the form of a continuum, rather than abrupt separation, implying any form of clustering would require gradient borders rather than clear boundaries.</p>
<p>K-means clustering algorithms identified k = 2 as the best partition according to the main internal validity metrics. Specifically, k = 2 achieved the highest silhouette score (0.196) and Calinski-Harabasz index (200.93), with values decreasing as k increased (<a href="#t-3">Table 3</a>). Bootstrap stability was also good: raw k = 2 partitions attained mean ARI of 0.893 with standard deviation of 0.084 (<a href="#t-4">Table 4</a>).</p>
<p>Feature-level inspection provided us with a biologically-plausible interpretation, where the top-ranked cluster-separating variables were dominated by signal-enhancement ratio (SER), peak-enhancement (PE), entropy, homogeneity, and similar enhancement-texture descriptors. Cohen d values exceeded 2.2 for top-ranked SER entropy and sum-entropy features (See <a href="#t-5">Table 5</a>). This clustering phenotype’s appearance is arguably vascularity-like: one group manifests more spatially heterogeneous enhancement while the other manifests relatively homogeneous enhancement behavior. Whether a genuine biological foundation is true or not is irrelevant in this case as this is used to showcase how “biological plausibility” can be attached to the partitions.</p>
<p>Finally, the raw partition looked prognostically meaningful in the HR+/HER2+ subgroup. Of the 101 patients with successful follow-up truncation, Cluster 0 had 55 patients and 2 recurrences while Cluster 1 had 46 patients and 8 recurrences. Kaplan-Meier curves were visibly separated (<a href="#f-3">Figure 3</a>), log-rank test was significant (p = 0.010), and unadjusted Cox model estimated HR = 4.76 for Cluster 1 vs Cluster 0 (95% CI 1.22-18.61; p = 0.02) as seen in <a href="#t-6">Table 6</a>. In conventional circumstances, those results might validate as a reproducible vascularity-like prognostic phenotype. In this manuscript, they form the counterexample challenged by the falsification chain.</p>
<div id="t-2" class="table-caption">
<p>Table 2. Variance explained by the leading principal components.</p>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Principal component</th>
<th>Explained variance ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>PC1</td>
<td>0.1549</td>
</tr>
<tr class="even">
<td>PC2</td>
<td>0.0958</td>
</tr>
<tr class="odd">
<td>PC3</td>
<td>0.0775</td>
</tr>
<tr class="even">
<td>PC4</td>
<td>0.0532</td>
</tr>
<tr class="odd">
<td>PC5</td>
<td>0.0495</td>
</tr>
<tr class="even">
<td>PC6</td>
<td>0.0374</td>
</tr>
<tr class="odd">
<td>PC7</td>
<td>0.0354</td>
</tr>
<tr class="even">
<td>PC8</td>
<td>0.0296</td>
</tr>
<tr class="odd">
<td>PC9</td>
<td>0.0241</td>
</tr>
<tr class="even">
<td>PC10</td>
<td>0.0215</td>
</tr>
</tbody>
</table>
<div id="f-1" class="manuscript-figure">
<div id="4cf87438" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="2">
<div class="light-content">
<p><a href="figures/fig-scree-light.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="figures/fig-scree-light.svg" class="img-fluid" alt=""></a></p>
</div>
<div class="dark-content">
<p><a href="figures/fig-scree-dark.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-2"><img src="figures/fig-scree-dark.svg" class="img-fluid" alt=""></a></p>
</div>
</div>
</div>
</div>
<div class="figure-caption">
<p>Figure 1. Scree plot of the top 20 principal components.</p>
</div>
<div id="f-2" class="manuscript-figure">
<div id="588b5298" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="3">
<div class="light-content">
<p><a href="figures/fig-pca-projection-light.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-3"><img src="figures/fig-pca-projection-light.svg" class="img-fluid" alt=""></a></p>
</div>
<div class="dark-content">
<p><a href="figures/fig-pca-projection-dark.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-4"><img src="figures/fig-pca-projection-dark.svg" class="img-fluid" alt=""></a></p>
</div>
</div>
</div>
</div>
<div class="figure-caption">
<p>Figure 2. Projection of patients onto PC1 and PC2.</p>
</div>
<div id="t-3" class="table-caption">
<p>Table 3. Internal cluster validity across candidate k values.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>k</th>
<th>Silhouette score</th>
<th>Calinski-Harabasz index</th>
<th>Davies-Bouldin index</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td>0.195653</td>
<td>200.929867</td>
<td>1.955482</td>
</tr>
<tr class="even">
<td>3</td>
<td>0.157827</td>
<td>179.178568</td>
<td>1.932912</td>
</tr>
<tr class="odd">
<td>4</td>
<td>0.146367</td>
<td>149.854570</td>
<td>1.932116</td>
</tr>
<tr class="even">
<td>5</td>
<td>0.142494</td>
<td>134.423765</td>
<td>1.890264</td>
</tr>
<tr class="odd">
<td>6</td>
<td>0.134233</td>
<td>122.675314</td>
<td>1.864758</td>
</tr>
</tbody>
</table>
<div id="t-4" class="table-caption">
<p>Table 4. Bootstrap stability of the raw k=2 phenotype.</p>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bootstrap iterations</td>
<td>20</td>
</tr>
<tr class="even">
<td>Subsample fraction</td>
<td>0.80</td>
</tr>
<tr class="odd">
<td>Clustering method</td>
<td>K-means</td>
</tr>
<tr class="even">
<td>Number of clusters</td>
<td>2</td>
</tr>
<tr class="odd">
<td>Feature space</td>
<td>First 10 principal components</td>
</tr>
<tr class="even">
<td>Mean ARI</td>
<td>0.8931</td>
</tr>
<tr class="odd">
<td>SD ARI</td>
<td>0.0838</td>
</tr>
<tr class="even">
<td>Minimum ARI</td>
<td>0.7397</td>
</tr>
<tr class="odd">
<td>Maximum ARI</td>
<td>0.9837</td>
</tr>
</tbody>
</table>
<div id="t-5" class="table-caption">
<p>Table 5. Top raw cluster-separating radiomic features.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Feature</th>
<th>Mean C0</th>
<th>Mean C1</th>
<th>C1-C0</th>
<th>Cohen d</th>
<th>q-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SER_map_Entropy_tissue_T1</td>
<td>-0.552</td>
<td>0.964</td>
<td>1.516</td>
<td>2.214</td>
<td>1.09E-100</td>
</tr>
<tr class="even">
<td>SER_map_sum_entropy_tissue_T1</td>
<td>-0.552</td>
<td>0.963</td>
<td>1.515</td>
<td>2.211</td>
<td>2.70E-109</td>
</tr>
<tr class="odd">
<td>SER_map_std_dev_tissue_T1</td>
<td>0.550</td>
<td>-0.960</td>
<td>-1.510</td>
<td>-2.196</td>
<td>2.45E-164</td>
</tr>
<tr class="even">
<td>SER_map_difference_entropy_tissue_T1</td>
<td>-0.546</td>
<td>0.953</td>
<td>1.499</td>
<td>2.162</td>
<td>1.18E-103</td>
</tr>
<tr class="odd">
<td>SER_map_Homogeneity2_tissue_T1</td>
<td>0.540</td>
<td>-0.942</td>
<td>-1.483</td>
<td>-2.114</td>
<td>2.46E-95</td>
</tr>
<tr class="even">
<td>SER_map_Homogeneity1_tissue_T1</td>
<td>0.539</td>
<td>-0.940</td>
<td>-1.479</td>
<td>-2.104</td>
<td>1.70E-97</td>
</tr>
<tr class="odd">
<td>PE_map_std_dev_tissue_T1</td>
<td>0.532</td>
<td>-0.927</td>
<td>-1.459</td>
<td>-2.047</td>
<td>1.72E-164</td>
</tr>
</tbody>
</table>
<div id="f-3" class="manuscript-figure">
<div id="ccfd282a" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="4">
<div class="light-content">
<p><a href="figures/fig-km-light.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-5"><img src="figures/fig-km-light.svg" class="img-fluid" alt=""></a></p>
</div>
<div class="dark-content">
<p><a href="figures/fig-km-dark.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-6"><img src="figures/fig-km-dark.svg" class="img-fluid" alt=""></a></p>
</div>
</div>
</div>
</div>
<div class="figure-caption">
<p>Figure 3. Recurrence-free survival in HR+/HER2+ patients by raw radiomic cluster.</p>
</div>
<div id="t-6" class="table-caption">
<p>Table 6. Fragile unadjusted HR+/HER2+ recurrence-free-survival signal by raw radiomic cluster.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Analysis</th>
<th>Estimate</th>
<th>95% CI</th>
<th>p-value</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cluster 0</td>
<td>55 patients; 2 events; event rate 3.6%</td>
<td>-</td>
<td>-</td>
<td>Lower unadjusted recurrence burden.</td>
</tr>
<tr class="even">
<td>Cluster 1</td>
<td>46 patients; 8 events; event rate 17.4%</td>
<td>-</td>
<td>-</td>
<td>Higher unadjusted recurrence burden; not sufficient for biomarker interpretation.</td>
</tr>
<tr class="odd">
<td>Log-rank test</td>
<td>-</td>
<td>-</td>
<td>0.010</td>
<td>Significant unadjusted RFS difference.</td>
</tr>
<tr class="even">
<td>Cox: Cluster 1 vs Cluster 0</td>
<td>HR=4.76</td>
<td>1.22-18.61</td>
<td>0.02</td>
<td>Large but imprecise unadjusted effect based on only 10 events.</td>
</tr>
</tbody>
</table>
</section>
<section id="key-message-2-the-apparent-phenotype-is-acquisition-dominated-not-subtype-defined" class="level2">
<h2 class="anchored" data-anchor-id="key-message-2-the-apparent-phenotype-is-acquisition-dominated-not-subtype-defined">4.2 Key message 2: the apparent phenotype is acquisition-dominated, not subtype-defined</h2>
<p>Once technical acquisition factors are examined, it is found that the raw cluster becomes significantly associated with manufacturer (p = 8.0 x 10-104) while insignificant with molecular subtype (p = 0.146) or recurrence (p = 0.766) as shown in <a href="#t-7">Table 7</a>. The contingency signal was not subtle: A closer look at the data reveals that Cluster 0 was largely comprised of GE machine acquisitions, as opposed to Cluster 1, which predominantly featured Siemens (as shown in <a href="#t-8">Table 8</a> and <a href="#f-4">Figure 4</a>).</p>
<p>When the PC1-PC2 projections are labeled by manufacturers rather than cluster identity, the partitions become almost indistinguishable between the two graphs (<a href="#f-5">Figure 5</a>). In other words, the clustering algorithms partitioned the data according to the machine that captured the image. Examining the PC1 more closely, reveals that TR, TE, the acquisition matrix, and manufacturer were all more closely tied to PC1 than molecular subtype (which remained below about 0.04 across the top ten PCs), with eta-squared(s) reported as approximately 0.76 for TR, 0.63 for TE, 0.57 for the acquisition matrix, and 0.49 for manufacturer in <a href="#t-9">Table 9</a>. This is a standard example of the stability trap. The partition is not noisy; it is simply stable. In this context, high bootstrap ARI should be interpreted not as evidence for the clusters’ biological signal, but rather as evidence that the scanner-domain structure is itself reproducible.</p>
<div id="t-7" class="table-caption">
<p>Table 7. Association of raw cluster assignment with clinical and technical variables.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>p-value</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Manufacturer</td>
<td>8.022438E-104</td>
<td>Strong association with raw cluster assignment.</td>
</tr>
<tr class="even">
<td>Molecular subtype</td>
<td>0.145796</td>
<td>No significant association with raw cluster assignment.</td>
</tr>
<tr class="odd">
<td>Recurrence event</td>
<td>0.765626</td>
<td>No significant whole-cohort association with recurrence.</td>
</tr>
</tbody>
</table>
<div id="t-8" class="table-caption">
<p>Table 8. Raw cluster assignment by MRI manufacturer.</p>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Cluster</th>
<th>GE</th>
<th>Siemens</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>547</td>
<td>39</td>
<td>Cluster 0 is predominantly GE.</td>
</tr>
<tr class="even">
<td>1</td>
<td>81</td>
<td>255</td>
<td>Cluster 1 is predominantly Siemens.</td>
</tr>
</tbody>
</table>
<div id="f-4" class="manuscript-figure">
<div id="f5102e75" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="5">
<div class="light-content">
<p><a href="figures/fig-composition-light.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-7"><img src="figures/fig-composition-light.svg" class="img-fluid" alt=""></a></p>
</div>
<div class="dark-content">
<p><a href="figures/fig-composition-dark.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-8"><img src="figures/fig-composition-dark.svg" class="img-fluid" alt=""></a></p>
</div>
</div>
</div>
</div>
<div class="figure-caption">
<p>Figure 4. Manufacturer composition within each raw radiomic cluster.</p>
</div>
<div id="f-5" class="manuscript-figure">
<div class="pca-toggle">
  <input type="radio" name="pca-view" id="pca-view-cluster" checked="">
  <input type="radio" name="pca-view" id="pca-view-vendor">
  <div class="pca-tabs">
    <label for="pca-view-cluster">Colored by radiomic cluster</label>
    <label for="pca-view-vendor">Colored by manufacturer</label>
  </div>
  <div class="pca-stack">
    <div class="view v-cluster">
      <div class="light-content"><img src="figures/fig-pca-by-cluster-light.svg" alt="PCA space colored by radiomic cluster"></div>
      <div class="dark-content"><img src="figures/fig-pca-by-cluster-dark.svg" alt="PCA space colored by radiomic cluster"></div>
    </div>
    <div class="view v-vendor">
      <div class="light-content"><img src="figures/fig-pca-by-vendor-light.svg" alt="PCA space colored by manufacturer"></div>
      <div class="dark-content"><img src="figures/fig-pca-by-vendor-dark.svg" alt="PCA space colored by manufacturer"></div>
    </div>
  </div>
</div>
</div>
<div class="figure-caption">
<p>Figure 5. Raw PCA space colored by radiomic cluster and by manufacturer..</p>
</div>
<div id="t-9" class="table-caption">
<p>Table 9. Acquisition-variable dominance on the leading radiomic axis.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>PC1 eta-squared or association strength</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>TR</td>
<td>0.76</td>
<td>Dominant pulse-sequence association with PC1.</td>
</tr>
<tr class="even">
<td>TE</td>
<td>0.63</td>
<td>Strong pulse-sequence association with PC1.</td>
</tr>
<tr class="odd">
<td>Acquisition matrix</td>
<td>0.57</td>
<td>Strong technical association with PC1.</td>
</tr>
<tr class="even">
<td>Manufacturer</td>
<td>0.49</td>
<td>Strong scanner-domain association with PC1.</td>
</tr>
<tr class="odd">
<td>Field strength</td>
<td>0.09</td>
<td>Weaker than TR/TE/manufacturer.</td>
</tr>
<tr class="even">
<td>Slice thickness</td>
<td>0.07</td>
<td>Weaker than TR/TE/manufacturer.</td>
</tr>
<tr class="odd">
<td>Molecular subtype</td>
<td>&lt;=0.04 across top-10 PCs</td>
<td>Biological subtype explains much less leading-PC structure.</td>
</tr>
</tbody>
</table>
</section>
<section id="key-message-3-harmonization-preserves-bootstrap-stability-but-destroys-partition-identity" class="level2">
<h2 class="anchored" data-anchor-id="key-message-3-harmonization-preserves-bootstrap-stability-but-destroys-partition-identity">4.3 Key message 3: harmonization preserves bootstrap stability but destroys partition identity</h2>
<p>Techniques used to phase out acquisition effects like residualization and ComBat eliminated the visible manufacturer association, but in the process destroyed the phenotypical discovery. The ARI between residualized labels and raw labels was 0.056, while for ComBat harmonization ARI versus raw labels was 0.065. Both techniques showcased a near-total loss of the original partition identity. The important observation is that clusterability was retained and that both the residualized space and ComBat space could be split into internally consistent two-cluster solutions (with mean bootstrap ARI 0.919 and 0.903 respectively) (See <a href="#t-10">Table 10</a> and <a href="#f-7">Figure 7</a>). <a href="#f-6">Figure 6</a> communicates the same result visually where the raw cluster geometry matches the manufacturer geometry, but the new residualized cluster geometry no longer represents the previous raw partition.</p>
<p>The retention of clusterability despite removal of partition identity separates two concepts that are often confused. Bootstrap stability asks if a cluster solution can be repeated given the data condition. Partition identity asks if the same patients are clustered after a technical adjustment. This report found that stability is maintained while identity is not. Any validation workflow focusing on stability alone would have certified this failure as success.</p>
<div id="f-6" class="manuscript-figure">
<div id="5844ad5e" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="6">
<div class="light-content">
<p><a href="figures/fig-identity-scramble-light.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-9"><img src="figures/fig-identity-scramble-light.svg" class="img-fluid" alt=""></a></p>
</div>
<div class="dark-content">
<p><a href="figures/fig-identity-scramble-dark.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-10"><img src="figures/fig-identity-scramble-dark.svg" class="img-fluid" alt=""></a></p>
</div>
</div>
</div>
</div>
<div class="figure-caption">
<p>Figure 6. Comparison of latent structure before and after manufacturer residualization.</p>
</div>
<div id="f-7" class="manuscript-figure">
<div id="618f98b8" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="7">
<div class="light-content">
<p><a href="figures/fig-bootstrap-light.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-11"><img src="figures/fig-bootstrap-light.svg" class="img-fluid" alt=""></a></p>
</div>
<div class="dark-content">
<p><a href="figures/fig-bootstrap-dark.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-12"><img src="figures/fig-bootstrap-dark.svg" class="img-fluid" alt=""></a></p>
</div>
</div>
</div>
</div>
<div class="figure-caption">
<p>Figure 7. Bootstrap stability across raw and harmonized conditions.</p>
</div>
<div id="t-10" class="table-caption">
<p>Table 10. Stability versus identity across raw and harmonized conditions.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Condition</th>
<th>Mean bootstrap ARI</th>
<th>SD ARI</th>
<th>ARI versus raw labels</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Raw</td>
<td>0.893139</td>
<td>0.083795</td>
<td>1.000000</td>
<td>Stable baseline partition.</td>
</tr>
<tr class="even">
<td>Manufacturer residualized</td>
<td>0.918669</td>
<td>0.046946</td>
<td>0.056485</td>
<td>Stable but nearly unrelated to raw labels.</td>
</tr>
<tr class="odd">
<td>ComBat harmonized</td>
<td>0.902907</td>
<td>0.057623</td>
<td>0.064988</td>
<td>Stable but nearly unrelated to raw labels.</td>
</tr>
</tbody>
</table>
<div id="t-11" class="table-caption">
<p>Table 11. Association tests after technical harmonization.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Cluster type</th>
<th>Manufacturer p</th>
<th>Molecular subtype p</th>
<th>Recurrence p</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Raw cluster</td>
<td>8.022438E-104</td>
<td>0.145796</td>
<td>0.765626</td>
<td>Strong manufacturer dependence.</td>
</tr>
<tr class="even">
<td>Residualized cluster</td>
<td>0.529964</td>
<td>0.716945</td>
<td>0.074725</td>
<td>Manufacturer dependence removed; clinical signal borderline only.</td>
</tr>
<tr class="odd">
<td>ComBat cluster</td>
<td>0.176522</td>
<td>0.809070</td>
<td>0.055758</td>
<td>Manufacturer dependence attenuated; clinical signal borderline only.</td>
</tr>
</tbody>
</table>
</section>
<section id="key-message-4-neither-the-hrher2-signal-nor-the-residual-size-linked-structure-supports-a-biomarker-claim" class="level2">
<h2 class="anchored" data-anchor-id="key-message-4-neither-the-hrher2-signal-nor-the-residual-size-linked-structure-supports-a-biomarker-claim">4.4 Key message 4: neither the HR+/HER2+ signal nor the residual size-linked structure supports a biomarker claim</h2>
<p>Post-harmonization indicates loss of the HR+/HER2+ survival signal. When forced into a Cox model along with raw cluster, the cluster HR dropped to 2.48 and was no longer significant (95% CI 0.46-13.39; p=0.291). Manufacturer itself was also insignificant in that tiny subgroup (HR=2.99; p=0.200), but there are too few degrees of freedom to properly test two correlated predictors with only 10 events (<a href="#t-13">Table 13</a>).</p>
<p>After technical confounders were removed, there remained a structure. However, it is more accurately characterized as a size-correlated residue than as an orthogonal discovery. Clusters determined after harmonization were no longer detectably coupled with manufacturer, and they associated most strongly with tumor bounding-box volume in the extended analysis (p∼10^-26). That residual structure did not meet the prespecified biomarker validation thresholds summarized in <a href="#t-14">Table 14</a>: The recurrence association was weak, radiomic scores did not predict recurrence after clinical covariates, and scores were not sufficiently directionally consistent within vendors to make a biomarker claim.</p>
<p>The appropriate conclusion is therefore not that radiomic clustering is useless but rather that the raw apparent discovery must be downgraded to a false positive after going through acquisition-aware falsification. The lesson is therefore the following</p>
<p>Perform identity checks, check for harmonization sensitivity and test for clinical validity before interpreting stable clusters as phenotypes.</p>
<div id="t-13" class="table-caption">
<p>Table 13. Manufacturer-adjusted Cox model in the HR+/HER2+ subgroup.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Covariate</th>
<th>Coefficient</th>
<th>Hazard ratio</th>
<th>95% CI</th>
<th>p-value</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Raw cluster</td>
<td>0.908162</td>
<td>2.479761</td>
<td>0.459408-13.385089</td>
<td>0.291085</td>
<td>Cluster effect attenuates and loses significance.</td>
</tr>
<tr class="even">
<td>Manufacturer: Siemens vs GE</td>
<td>1.096711</td>
<td>2.994301</td>
<td>0.559256-16.031719</td>
<td>0.200157</td>
<td>Non-significant in sparse subgroup; correlated with cluster.</td>
</tr>
</tbody>
</table>
<div id="t-14" class="table-caption">
<p>Table 14. Prespecified biomarker criteria for the post-harmonization residual structure.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Criterion</th>
<th>Observed result</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Endpoint association</td>
<td>Cluster-level recurrence signals were borderline or non-robust, and adjusted clinical models did not establish a durable recurrence association.</td>
<td>Not met</td>
</tr>
<tr class="even">
<td>Incremental predictive value</td>
<td>Radiomic/vascularity-augmented models did not improve recurrence prediction beyond clinical features in nested cross-validation.</td>
<td>Not met</td>
</tr>
<tr class="odd">
<td>Within-vendor direction consistency</td>
<td>Direction and magnitude were not sufficiently reliable across vendor-restricted analyses to support a biomarker claim.</td>
<td>Not met</td>
</tr>
<tr class="even">
<td>Overall conclusion</td>
<td>Residual structure is vendor-cleaner and size-linked, but it is not validated as a biological or clinical phenotype in this cohort.</td>
<td>Fails biomarker threshold</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="discussion" class="level1">
<h1>5. Discussion</h1>
<section id="main-finding-the-negative-result-is-the-result" class="level2">
<h2 class="anchored" data-anchor-id="main-finding-the-negative-result-is-the-result">5.1 Main finding: the negative result is the result</h2>
<p>The main takeaway of this report is as such: a radiomic partition can be internally stable, visually coherent, and apparently prognostic while failing to represent a biological subgroup. Our initial two group partitions looked compelling when ranked against a standard metric, where it was reproducible when resampled, had a vascularity associated profile and hinted at a promising HR+/HER2+ phenotype with an increase in recurrence, but under closer inspection, the partitions aligned mostly with scanner manufacturer and pulse-sequence.</p>
<p>This brings us back to the utility of stability trap terminology. Raw phenotype was not meaningless noise, but rather it was stable because the acquisition signal was stable. High bootstrap scores became misleading because they were interpreted as signals of biological truth. Instead, the more accurate inference is more limited: the clustering algorithm identified and recovered a strong and reproducible signal present in the radiomic feature matrix. The falsification chain then demonstrates that dominant signal is primarily technical. If we must extract a positive finding from this work, therefore, it is the invalidation of the phenotype claim rather than identification of a new phenotype.</p>
</section>
<section id="dangers-of-language" class="level2">
<h2 class="anchored" data-anchor-id="dangers-of-language">5.2 Dangers of Language</h2>
<p>Feature-wise, the cluster-separating features made sense. Signal-enhancement-ratio (SER) entropy, SER homogeneity, peak enhancement (PE) variability, certain enhancement-volume ratios, and wash-in/efflux descriptors naturally suggest increased versus decreased vascularity or perfusion. Enhancement-history descriptors are especially interpretable that way in breast DCE-MRI since tumor enhancement behavior is already the central radiological finding on this exam. Those same qualities make the stability trap so malicious, though: conceptually familiar language can too easily coat a technically induced partition.</p>
<p>That is not to say the report should avoid using biologically plausible language because Enhancement features are not biologically meaningless; patients just tend not to cluster cleanly by vascular biology in early breast cancer. But that biological plausibility is not evidence. Absent acquisition vulnerability, language would not be an issue, but when leading features are acquisition sensitive, vascularity descriptors become hypothesis rather than confirmation. The profile becomes plausible but hypothetical (“these features are known to be associated with vascularity, and the clusters separate on those features”) until the acquisition-ware checks are passed.</p>
</section>
<section id="cluster-stability-and-partition-identity-are-separate-validation-targets" class="level2">
<h2 class="anchored" data-anchor-id="cluster-stability-and-partition-identity-are-separate-validation-targets">5.3 Cluster stability and partition identity are separate validation targets</h2>
<p>Separately, harmonization explains why cluster stability and partition identity are different validation goals. Harmonization did not destroy cluster stability; residualization and Combat produced perfectly stable yet novel two-cluster solutions. The important change was that cluster patient labels were no longer the same before and after harmonization.</p>
<p>In practical terms, radiomic validation will require more than silhouette scores and bootstrap stabilization. A completed phenotype paper should minimally report cluster preservation after acquisition correction, evaluation of leading PCs for technical versus biological dependencies, harmonization sensitivity of any clinical associations, and post-harmonization structure’s conformance to any prespecified biomarker criteria.</p>
</section>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">5.5 Limitations</h2>
<p>This study has several limitations. First, the survival analysis pertaining to HR+/HER2+ should be taken with caution due to low sample count (N=10), a problem central to medical imaging analysis. The divergence between the subgroups is dramatic, but the CI is wide. More patients would be needed if one wishes to quantify any subtype-specific prognostic effect.</p>
<p>Second, k-means clustering utilizing principal components feature space was legible and justified for the purposes of this falsification exercise. But to further strengthen the argument of technical confounding, it is recommended to apply more unsupervised classifiers.</p>
<p>Lastly, harmonization is not ground truth. While ComBat and residualization are able to remove technical effects the post-harmonization subgroup are not inherently biological. One must treat the harmonization as an adversary, not an assurance of validity.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>6. Conclusion</h1>
<p>Our study demonstrates that radiomic phenotypes can be internally stable, visually coherent and apparently prognostic, but still fail multiple tests of biological identity. Using a 922-patient multi-vendor breast MRI dataset, we showed that even a standard unsupervised workflow will produce an internally stable, vascularity- like two-cluster solution that appears to carry strong prognostic information for HR+/HER2+ survival. Acquisition-aware falsification tests thus changed the interpretation of our initial findings: (a) leading PCs and raw cluster labels were dominated by manufacturer and pulse-sequence structure; (b) manufacturer harmonization substantially weakened the survival association; and (c) residualization or ComBat entirely supplanted our original patient partition but maintained its internal stability. The broadest claim we make is methodological: Stability is best viewed as the first step of radiomic phenotype validation, not the last. Internal consistency should be accompanied by a battery of tests including multi-condition discovery, harmonization sensitivity and within-vendor sanity checks. While our analysis was focused on breast MRI, the general principles apply to any multi-center or multi-vendor radiomics/imaging-AI context in which technical variance may be stable enough to confound biology.</p>
</section>
<section id="supplementary-material" class="level1">
<h1>Supplementary Material</h1>
<div id="t-s1" class="table-caption">
<p>Supplementary Table S1. Structural interpretation of the raw PCA and clustering outputs.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Item</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Scree plot</td>
<td>Variance declines progressively after the first few PCs; structure is present but not concentrated in a single biological axis.</td>
</tr>
<tr class="even">
<td>PC1-PC2 scatter</td>
<td>Patients form a continuous distribution without clean natural separation.</td>
</tr>
<tr class="odd">
<td>Raw k=2 clusters</td>
<td>Cluster separation occurs primarily along the dominant PC axis.</td>
</tr>
<tr class="even">
<td>Manufacturer coloring</td>
<td>Manufacturer distribution closely mirrors the raw cluster geometry.</td>
</tr>
<tr class="odd">
<td>Residualized clusters</td>
<td>Technical correction produces a different stable partition.</td>
</tr>
</tbody>
</table>
<div id="f-s1" class="manuscript-figure">
<div id="29c4543a" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="8">
<div class="light-content">
<p><a href="figures/fig-cluster-within-manufacturer-light.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-13"><img src="figures/fig-cluster-within-manufacturer-light.svg" class="img-fluid" alt=""></a></p>
</div>
<div class="dark-content">
<p><a href="figures/fig-cluster-within-manufacturer-dark.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-14"><img src="figures/fig-cluster-within-manufacturer-dark.svg" class="img-fluid" alt=""></a></p>
</div>
</div>
</div>
</div>
<div class="figure-caption">
<p>Supplementary Figure S1. Raw radiomic cluster distribution within each manufacturer.</p>
</div>
<div id="f-s2" class="manuscript-figure">
<div id="2c8b7a87" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="9">
<div class="light-content">
<p><a href="figures/fig-pca-by-vendor-light.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-15"><img src="figures/fig-pca-by-vendor-light.svg" class="img-fluid" alt=""></a></p>
</div>
<div class="dark-content">
<p><a href="figures/fig-pca-by-vendor-dark.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-16"><img src="figures/fig-pca-by-vendor-dark.svg" class="img-fluid" alt=""></a></p>
</div>
</div>
</div>
</div>
<div class="figure-caption">
<p>Supplementary Figure S2. PCA space colored by manufacturer.</p>
</div>
<div id="f-s3" class="manuscript-figure">
<div id="453714e2" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="10">
<div class="light-content">
<p><a href="figures/fig-pca-by-cluster-light.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-17"><img src="figures/fig-pca-by-cluster-light.svg" class="img-fluid" alt=""></a></p>
</div>
<div class="dark-content">
<p><a href="figures/fig-pca-by-cluster-dark.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-18"><img src="figures/fig-pca-by-cluster-dark.svg" class="img-fluid" alt=""></a></p>
</div>
</div>
</div>
</div>
<div class="figure-caption">
<p>Supplementary Figure S3. PCA space colored by raw radiomic cluster.</p>
</div>
<div id="t-s2" class="table-caption">
<p>Supplementary Table S2. Raw cluster assignment by molecular subtype.</p>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Cluster</th>
<th>Subtype 0</th>
<th>Subtype 1</th>
<th>Subtype 2</th>
<th>Subtype 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>383</td>
<td>56</td>
<td>41</td>
<td>106</td>
</tr>
<tr class="even">
<td>1</td>
<td>212</td>
<td>48</td>
<td>18</td>
<td>58</td>
</tr>
</tbody>
</table>
<div id="t-s3" class="table-caption">
<p>Supplementary Table S3. Raw cluster assignment by recurrence event.</p>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Cluster</th>
<th>No recurrence</th>
<th>Recurrence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>527</td>
<td>57</td>
</tr>
<tr class="even">
<td>1</td>
<td>306</td>
<td>30</td>
</tr>
</tbody>
</table>
<div id="t-s4" class="table-caption">
<p>Supplementary Table S4. Biological interpretation of dominant feature patterns.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Feature category</th>
<th>Cluster pattern</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SER entropy features</td>
<td>Elevated in Cluster 1</td>
<td>Greater enhancement heterogeneity and spatial disorder.</td>
</tr>
<tr class="even">
<td>SER homogeneity features</td>
<td>Elevated in Cluster 0</td>
<td>More spatially uniform enhancement behavior.</td>
</tr>
<tr class="odd">
<td>SER standard deviation</td>
<td>Elevated in Cluster 0</td>
<td>Greater enhancement intensity dispersion in the more homogeneous phenotype.</td>
</tr>
<tr class="even">
<td>Enhancement-volume ratios</td>
<td>Strongly cluster-separating</td>
<td>Differences in global vascular enhancement burden.</td>
</tr>
<tr class="odd">
<td>Wash-in/washout slope features</td>
<td>Strongly cluster-separating</td>
<td>Distinct enhancement kinetics between raw clusters.</td>
</tr>
<tr class="even">
<td>Overall phenotype structure</td>
<td>Enhancement-dominant</td>
<td>Putative vascularity-related radiomic phenotype before falsification.</td>
</tr>
</tbody>
</table>
<div id="t-s5" class="table-caption">
<p>Supplementary Table S5. Claim-status summary after falsification.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Claim</th>
<th>Status in this cohort</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Raw two-cluster phenotype is internally stable</td>
<td>Supported by bootstrap ARI.</td>
</tr>
<tr class="even">
<td>Raw phenotype has vascularity-like feature appearance</td>
<td>Supported by SER/PE/enhancement-texture feature ranking, but treated only as a plausible counterexample.</td>
</tr>
<tr class="odd">
<td>Raw phenotype is an independent biological biomarker</td>
<td>Not supported after technical adjudication.</td>
</tr>
<tr class="even">
<td>Leading PCs are more technical than subtype-linked</td>
<td>Supported by manufacturer/TR/TE/acquisition-matrix dominance.</td>
</tr>
<tr class="odd">
<td>Cluster stability and cluster identity are equivalent</td>
<td>Refuted: harmonized partitions remain stable but lose raw identity.</td>
</tr>
<tr class="even">
<td>Residual post-harmonization structure is a validated biomarker</td>
<td>Not supported; fails prespecified biomarker criteria.</td>
</tr>
<tr class="odd">
<td>The framework generalizes beyond breast MRI</td>
<td>Methodologically applicable to multi-vendor and multicenter imaging settings.</td>
</tr>
</tbody>
</table>
</section>
<section id="references" class="level1">
<h1>References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-aerts2014" class="csl-entry" role="listitem">
Aerts, Hugo J. W. L., Emmanuel Rios Velazquez, Ralph T. H. Leijenaar, et al. 2014. <span>“Decoding Tumour Phenotype by Noninvasive Imaging Using a Quantitative Radiomics Approach.”</span> <em>Nature Communications</em> 5 (1): 4006. <a href="https://doi.org/10.1038/ncomms5006">https://doi.org/10.1038/ncomms5006</a>.
</div>
<div id="ref-berenguer2018" class="csl-entry" role="listitem">
Berenguer, Roberto, María del Rosario Pastor-Juan, Jesús Canales-Vázquez, et al. 2018. <span>“Radiomics of <span>CT</span> Features May Be Nonreproducible and Redundant: Influence of <span>CT</span> Acquisition Parameters.”</span> <em>Radiology</em> 288 (2): 407–15. <a href="https://doi.org/10.1148/radiol.2018172361">https://doi.org/10.1148/radiol.2018172361</a>.
</div>
<div id="ref-bhooshan2010" class="csl-entry" role="listitem">
Bhooshan, Neha, Maryellen L. Giger, Sanaz A. Jansen, Hui Li, Li Lan, and Gillian M. Newstead. 2010. <span>“Cancerous Breast Lesions on Dynamic Contrast-Enhanced <span>MR</span> Images: Computerized Characterization for Image-Based Prognostic Markers.”</span> <em>Radiology</em> 254 (3): 680–90. <a href="https://doi.org/10.1148/radiol.09090838">https://doi.org/10.1148/radiol.09090838</a>.
</div>
<div id="ref-collins2015" class="csl-entry" role="listitem">
Collins, Gary S., Johannes B. Reitsma, Douglas G. Altman, and Karel G. M. Moons. 2015. <span>“Transparent Reporting of a Multivariable Prediction Model for Individual Prognosis or Diagnosis (<span>TRIPOD</span>): The <span>TRIPOD</span> Statement.”</span> <em>British Journal of Surgery</em> 102 (3): 148–58. <a href="https://doi.org/10.1002/bjs.9736">https://doi.org/10.1002/bjs.9736</a>.
</div>
<div id="ref-daano2020" class="csl-entry" role="listitem">
Da-Ano, Ronrick, Dimitris Visvikis, and Mathieu Hatt. 2020. <span>“Harmonization Strategies for Multicenter Radiomics Investigations.”</span> <em>Physics in Medicine &amp; Biology</em> 65 (24): 24TR02. <a href="https://doi.org/10.1088/1361-6560/aba798">https://doi.org/10.1088/1361-6560/aba798</a>.
</div>
<div id="ref-doran2021" class="csl-entry" role="listitem">
<span class="nocase">Doran, Simon J., Santosh Kumar, Matthew Orton, et al.</span> 2021. <span>“<span>‘Real-World’</span> Radiomics from Multi-Vendor <span>MRI</span>: An Original Retrospective Study on the Prediction of Nodal Status and Disease Survival in Breast Cancer, as an Exemplar to Promote Discussion of the Wider Issues.”</span> <em>Cancer Imaging</em> 21 (1): 37. <a href="https://doi.org/10.1186/s40644-021-00406-6">https://doi.org/10.1186/s40644-021-00406-6</a>.
</div>
<div id="ref-duron2019" class="csl-entry" role="listitem">
Duron, Loic, Daniel Balvay, Saïd Vande Perre, et al. 2019. <span>“Gray-Level Discretization Impacts Reproducible <span>MRI</span> Radiomics Texture Features.”</span> <em>PLOS ONE</em> 14 (3): e0213459. <a href="https://doi.org/10.1371/journal.pone.0213459">https://doi.org/10.1371/journal.pone.0213459</a>.
</div>
<div id="ref-fortin2018" class="csl-entry" role="listitem">
Fortin, Jean-Philippe, Nicholas Cullen, Yvette I. Sheline, et al. 2018. <span>“Harmonization of Cortical Thickness Measurements Across Scanners and Sites.”</span> <em>NeuroImage</em> 167: 104–20. <a href="https://doi.org/10.1016/j.neuroimage.2017.11.024">https://doi.org/10.1016/j.neuroimage.2017.11.024</a>.
</div>
<div id="ref-gillies2016" class="csl-entry" role="listitem">
Gillies, Robert J., Paul E. Kinahan, and Hedvig Hricak. 2016. <span>“Radiomics: Images Are More Than Pictures, They Are Data.”</span> <em>Radiology</em> 278 (2): 563–77. <a href="https://doi.org/10.1148/radiol.2015151169">https://doi.org/10.1148/radiol.2015151169</a>.
</div>
<div id="ref-handl2005" class="csl-entry" role="listitem">
Handl, Julia, Joshua Knowles, and Douglas B. Kell. 2005. <span>“Computational Cluster Validation in Post-Genomic Data Analysis.”</span> <em>Bioinformatics</em> 21 (15): 3201–12. <a href="https://doi.org/10.1093/bioinformatics/bti517">https://doi.org/10.1093/bioinformatics/bti517</a>.
</div>
<div id="ref-johnson2007" class="csl-entry" role="listitem">
Johnson, W. Evan, Cheng Li, and Ariel Rabinovic. 2007. <span>“Adjusting Batch Effects in Microarray Expression Data Using Empirical <span>B</span>ayes Methods.”</span> <em>Biostatistics</em> 8 (1): 118–27. <a href="https://doi.org/10.1093/biostatistics/kxj037">https://doi.org/10.1093/biostatistics/kxj037</a>.
</div>
<div id="ref-lambin2012" class="csl-entry" role="listitem">
Lambin, Philippe, Emmanuel Rios-Velazquez, Ralph Leijenaar, et al. 2012. <span>“Radiomics: Extracting More Information from Medical Images Using Advanced Feature Analysis.”</span> <em>European Journal of Cancer</em> 48 (4): 441–46. <a href="https://doi.org/10.1016/j.ejca.2011.11.036">https://doi.org/10.1016/j.ejca.2011.11.036</a>.
</div>
<div id="ref-leijenaar2015" class="csl-entry" role="listitem">
Leijenaar, Ralph T. H., Georgi Nalbantov, Sara Carvalho, et al. 2015. <span>“The Effect of <span>SUV</span> Discretization in Quantitative <span>FDG-PET</span> Radiomics: The Need for Standardized Methodology in Tumor Texture Analysis.”</span> <em>Scientific Reports</em> 5 (1): 11075. <a href="https://doi.org/10.1038/srep11075">https://doi.org/10.1038/srep11075</a>.
</div>
<div id="ref-leithner2022" class="csl-entry" role="listitem">
Leithner, Doris, Heiko Schöder, Alexander Haug, et al. 2022. <span>“Impact of <span>ComBat</span> Harmonization on <span>PET</span> Radiomics-Based Tissue Classification: A Dual-Center <span>PET/MRI</span> and <span>PET/CT</span> Study.”</span> <em>Journal of Nuclear Medicine</em> 63 (10): 1611–16. <a href="https://doi.org/10.2967/jnumed.121.263102">https://doi.org/10.2967/jnumed.121.263102</a>.
</div>
<div id="ref-li2018" class="csl-entry" role="listitem">
Li, Hongming, Maya Galperin-Aizenberg, Daniel Pryma, Charles B. Simone II, and Yong Fan. 2018. <span>“Unsupervised Machine Learning of Radiomic Features for Predicting Treatment Response and Overall Survival of Early Stage Non-Small Cell Lung Cancer Patients Treated with Stereotactic Body Radiation Therapy.”</span> <em>Radiotherapy and Oncology</em> 129 (2): 218–26. <a href="https://doi.org/10.1016/j.radonc.2018.06.025">https://doi.org/10.1016/j.radonc.2018.06.025</a>.
</div>
<div id="ref-lozano2024" class="csl-entry" role="listitem">
Lozano-Montoya, Jorge, and Ana Jimenez-Pastor. 2024. <span>“Harmonization in the Features Domain.”</span> In <em>Basics of Image Processing: The Facts and Challenges of Data Harmonization to Improve Radiomics Reproducibility</em>. Springer International Publishing. <a href="https://doi.org/10.1007/978-3-031-48446-9_7">https://doi.org/10.1007/978-3-031-48446-9_7</a>.
</div>
<div id="ref-lu2021" class="csl-entry" role="listitem">
Lu, Lin, Firas S. Ahmed, Oguz Akin, et al. 2021. <span>“Uncontrolled Confounders May Lead to False or Overvalued Radiomics Signature: A Proof of Concept Using Survival Analysis in a Multicenter Cohort of Kidney Cancer.”</span> <em>Frontiers in Oncology</em> 11: 638185. <a href="https://doi.org/10.3389/fonc.2021.638185">https://doi.org/10.3389/fonc.2021.638185</a>.
</div>
<div id="ref-mackin2015" class="csl-entry" role="listitem">
Mackin, Dennis, Xenia Fave, Lifei Zhang, et al. 2015. <span>“Measuring Computed Tomography Scanner Variability of Radiomics Features.”</span> <em>Investigative Radiology</em> 50 (11): 757–65. <a href="https://doi.org/10.1097/RLI.0000000000000180">https://doi.org/10.1097/RLI.0000000000000180</a>.
</div>
<div id="ref-nyul1999" class="csl-entry" role="listitem">
Nyúl, László G., and Jayaram K. Udupa. 1999. <span>“On Standardizing the <span>MR</span> Image Intensity Scale.”</span> <em>Magnetic Resonance in Medicine</em> 42 (6): 1072–81. <a href="https://doi.org/10.1002/(SICI)1522-2594(199912)42:6<1072::AID-MRM11>3.0.CO;2-M">https://doi.org/10.1002/(SICI)1522-2594(199912)42:6&lt;1072::AID-MRM11&gt;3.0.CO;2-M</a>.
</div>
<div id="ref-park2020" class="csl-entry" role="listitem">
Park, Ji Eun, Donghyun Kim, Ho Sung Kim, et al. 2020. <span>“Quality of Science and Reporting of Radiomics in Oncologic Studies: Room for Improvement According to Radiomics Quality Score and <span>TRIPOD</span> Statement.”</span> <em>European Radiology</em> 30 (1): 523–36. <a href="https://doi.org/10.1007/s00330-019-06360-z">https://doi.org/10.1007/s00330-019-06360-z</a>.
</div>
<div id="ref-parmar2015" class="csl-entry" role="listitem">
Parmar, Chintan, Patrick Grossmann, Derek Rietveld, Michelle M. Rietbergen, Philippe Lambin, and Hugo J. W. L. Aerts. 2015. <span>“Radiomic Machine-Learning Classifiers for Prognostic Biomarkers of Head and Neck Cancer.”</span> <em>Frontiers in Oncology</em> 5: 272. <a href="https://doi.org/10.3389/fonc.2015.00272">https://doi.org/10.3389/fonc.2015.00272</a>.
</div>
<div id="ref-pinker2018" class="csl-entry" role="listitem">
Pinker, Katja, Joanne Chin, Amy N. Melsaether, Elizabeth A. Morris, and Linda Moy. 2018. <span>“Precision Medicine and Radiogenomics in Breast Cancer: New Approaches Toward Diagnosis and Treatment.”</span> <em>Radiology</em> 287 (3): 732–47. <a href="https://doi.org/10.1148/radiol.2018172171">https://doi.org/10.1148/radiol.2018172171</a>.
</div>
<div id="ref-saha2018" class="csl-entry" role="listitem">
Saha, Ashirbani, Michael R. Harowicz, Lars J. Grimm, et al. 2018. <span>“A Machine Learning Approach to Radiogenomics of Breast Cancer: A Study of 922 Subjects and 529 <span>DCE-MRI</span> Features.”</span> <em>British Journal of Cancer</em> 119 (4): 508–16. <a href="https://doi.org/10.1038/s41416-018-0185-8">https://doi.org/10.1038/s41416-018-0185-8</a>.
</div>
<div id="ref-saha2021data" class="csl-entry" role="listitem">
Saha, Ashirbani, Michael R. Harowicz, Lars J. Grimm, et al. 2021. <em>Dynamic Contrast-Enhanced Magnetic Resonance Images of Breast Cancer Patients with Tumor Locations</em>. The Cancer Imaging Archive. <a href="https://doi.org/10.7937/TCIA.e3sv-re93">https://doi.org/10.7937/TCIA.e3sv-re93</a>.
</div>
<div id="ref-traverso2018" class="csl-entry" role="listitem">
Traverso, Alberto, Leonard Wee, Andre Dekker, and Robert Gillies. 2018. <span>“Repeatability and Reproducibility of Radiomic Features: A Systematic Review.”</span> <em>International Journal of Radiation Oncology, Biology, Physics</em> 102 (4): 1143–58. <a href="https://doi.org/10.1016/j.ijrobp.2018.05.053">https://doi.org/10.1016/j.ijrobp.2018.05.053</a>.
</div>
<div id="ref-yamamoto2012" class="csl-entry" role="listitem">
Yamamoto, Shota, Daniel D. Maki, Ronald L. Korn, and Michael D. Kuo. 2012. <span>“Radiogenomic Analysis of Breast Cancer Using <span>MRI</span>: A Preliminary Study to Define the Landscape.”</span> <em>American Journal of Roentgenology</em> 199 (3): 654–63. <a href="https://doi.org/10.2214/AJR.11.7824">https://doi.org/10.2214/AJR.11.7824</a>.
</div>
<div id="ref-zwanenburg2020" class="csl-entry" role="listitem">
<span class="nocase">Zwanenburg, Alex, Martin Vallières, Mahmoud A. Abdalah, et al.</span> 2020. <span>“The Image Biomarker Standardization Initiative: Standardized Quantitative Radiomics for High-Throughput Image-Based Phenotyping.”</span> <em>Radiology</em> 295 (2): 328–38. <a href="https://doi.org/10.1148/radiol.2020191145">https://doi.org/10.1148/radiol.2020191145</a>.
</div>
</div>


</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ma-mar-itan\.github\.io\/PortfolioWebsite\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Malek M. Itani</p>
</div>   
    <div class="nav-footer-center">
<p>Built with <a href="https://quarto.org">Quarto</a></p>
</div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Ma-Mar-Itan">
      <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/malek-ma-itani/">
      <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="mailto:Malek.Ma.Itani@gmail.com">
      <i class="bi bi-envelope" role="img" aria-label="Email">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>